"""The worker's view of the schema — generated, never edited (ADR 0032).

Regenerate with `pnpm --filter @better-answers/schema run generate:worker-view`;
the drift test fails CI when this file and the journal disagree in either
direction. The worker never migrates; this module is its read-only
knowledge of what the app's journal built, stamped with the migration id it was
generated from."""

MIGRATION_ID = "0006_identity-role-checks"

TABLES: dict[str, dict[str, str]] = {
    "index.chunk": {
        "id": "text NOT NULL",
        "workspace_id": "text NOT NULL",
        "content": "text NOT NULL",
        "embedding": "vector(1024) NOT NULL",
        "embedding_route_id": "text NOT NULL",
        "published_at": "timestamp with time zone",
        "sensitivity": "text NOT NULL",
        "audience": "text NOT NULL",
        "binding_id": "text NOT NULL",
    },
    "public.account": {
        "id": "text NOT NULL",
        "issuer": "text NOT NULL",
        "account_id": "text NOT NULL",
        "provider_id": "text NOT NULL",
        "user_id": "text NOT NULL",
        "access_token": "text",
        "refresh_token": "text",
        "id_token": "text",
        "access_token_expires_at": "timestamp with time zone",
        "refresh_token_expires_at": "timestamp with time zone",
        "scope": "text",
        "password": "text",
        "created_at": "timestamp with time zone NOT NULL",
        "updated_at": "timestamp with time zone NOT NULL",
    },
    "public.ingress_counter": {
        "scope": "text NOT NULL",
        "key": "text NOT NULL",
        "window_start": "timestamp with time zone NOT NULL",
        "count": "integer NOT NULL",
    },
    "public.invitation": {
        "id": "text NOT NULL",
        "workspace_id": "text NOT NULL",
        "email": "text NOT NULL",
        "role": "text",
        "status": "text NOT NULL",
        "expires_at": "timestamp with time zone NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "inviter_id": "text NOT NULL",
    },
    "public.jwks": {
        "id": "text NOT NULL",
        "public_key": "text NOT NULL",
        "private_key": "text NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "expires_at": "timestamp with time zone",
        "alg": "text",
        "crv": "text",
    },
    "public.llm_route": {
        "id": "text NOT NULL",
        "workspace_id": "text NOT NULL",
        "purpose": "llm_purpose NOT NULL",
        "provider": "text NOT NULL",
        "model": "text NOT NULL",
        "dimensions": "integer",
    },
    "public.mcp_call_counter": {
        "workspace_id": "text NOT NULL",
        "token_id": "text NOT NULL",
        "window_start": "timestamp with time zone NOT NULL",
        "count": "integer NOT NULL",
    },
    "public.member": {
        "id": "text NOT NULL",
        "workspace_id": "text NOT NULL",
        "user_id": "text NOT NULL",
        "role": "text NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
    },
    "public.oauth_access_token": {
        "id": "text NOT NULL",
        "token": "text NOT NULL",
        "client_id": "text NOT NULL",
        "session_id": "text",
        "user_id": "text",
        "reference_id": "text",
        "authorization_code_id": "text",
        "resources": "text[]",
        "requested_user_info_claims": "text[]",
        "refresh_id": "text",
        "expires_at": "timestamp with time zone NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "revoked": "timestamp with time zone",
        "confirmation": "jsonb",
        "scopes": "text[] NOT NULL",
    },
    "public.oauth_client": {
        "id": "text NOT NULL",
        "client_id": "text NOT NULL",
        "client_secret": "text",
        "client_discovery_id": "text",
        "disabled": "boolean",
        "skip_consent": "boolean",
        "enable_end_session": "boolean",
        "subject_type": "text",
        "scopes": "text[]",
        "client_credentials_scopes": "text[]",
        "user_id": "text",
        "created_at": "timestamp with time zone",
        "updated_at": "timestamp with time zone",
        "name": "text",
        "uri": "text",
        "icon": "text",
        "contacts": "text[]",
        "tos": "text",
        "policy": "text",
        "software_id": "text",
        "software_version": "text",
        "software_statement": "text",
        "redirect_uris": "text[] NOT NULL",
        "post_logout_redirect_uris": "text[]",
        "backchannel_logout_uri": "text",
        "backchannel_logout_session_required": "boolean",
        "token_endpoint_auth_method": "text",
        "application_type": "text",
        "jwks": "text",
        "jwks_uri": "text",
        "grant_types": "text[]",
        "response_types": "text[]",
        "require_pkce": "boolean",
        "dpop_bound_access_tokens": "boolean",
        "reference_id": "text",
        "metadata": "jsonb",
    },
    "public.oauth_client_assertion": {
        "id": "text NOT NULL",
        "expires_at": "timestamp with time zone NOT NULL",
    },
    "public.oauth_client_resource": {
        "id": "text NOT NULL",
        "client_id": "text NOT NULL",
        "resource_id": "text NOT NULL",
        "metadata": "jsonb",
        "created_at": "timestamp with time zone",
    },
    "public.oauth_consent": {
        "id": "text NOT NULL",
        "client_id": "text NOT NULL",
        "user_id": "text",
        "reference_id": "text",
        "resources": "text[]",
        "requested_user_info_claims": "text[]",
        "scopes": "text[] NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "updated_at": "timestamp with time zone NOT NULL",
    },
    "public.oauth_refresh_token": {
        "id": "text NOT NULL",
        "token": "text NOT NULL",
        "client_id": "text NOT NULL",
        "session_id": "text",
        "user_id": "text NOT NULL",
        "reference_id": "text",
        "authorization_code_id": "text",
        "resources": "text[]",
        "requested_user_info_claims": "text[]",
        "expires_at": "timestamp with time zone NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "revoked": "timestamp with time zone",
        "rotated_at": "timestamp with time zone",
        "rotation_replay_response": "text",
        "rotation_replay_expires_at": "timestamp with time zone",
        "auth_time": "timestamp with time zone",
        "confirmation": "jsonb",
        "scopes": "text[] NOT NULL",
    },
    "public.oauth_resource": {
        "id": "text NOT NULL",
        "identifier": "text NOT NULL",
        "name": "text NOT NULL",
        "access_token_ttl": "integer",
        "refresh_token_ttl": "integer",
        "signing_algorithm": "text",
        "signing_key_id": "text",
        "allowed_scopes": "text[]",
        "custom_claims": "jsonb",
        "dpop_bound_access_tokens_required": "boolean",
        "disabled": "boolean",
        "created_at": "timestamp with time zone",
        "updated_at": "timestamp with time zone",
        "policy_version": "integer",
        "metadata": "jsonb",
    },
    "public.rate_limit": {
        "id": "text NOT NULL",
        "key": "text NOT NULL",
        "count": "integer NOT NULL",
        "last_request": "bigint NOT NULL",
    },
    "public.session": {
        "id": "text NOT NULL",
        "expires_at": "timestamp with time zone NOT NULL",
        "token": "text NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "updated_at": "timestamp with time zone NOT NULL",
        "ip_address": "text",
        "user_agent": "text",
        "user_id": "text NOT NULL",
        "active_workspace_id": "text",
    },
    "public.user": {
        "id": "text NOT NULL",
        "name": "text NOT NULL",
        "email": "text NOT NULL",
        "email_verified": "boolean NOT NULL",
        "image": "text",
        "created_at": "timestamp with time zone NOT NULL",
        "updated_at": "timestamp with time zone NOT NULL",
        "credentials_revoked_at": "timestamp with time zone",
    },
    "public.verification": {
        "id": "text NOT NULL",
        "identifier": "text NOT NULL",
        "value": "text NOT NULL",
        "expires_at": "timestamp with time zone NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "updated_at": "timestamp with time zone NOT NULL",
    },
    "public.workspace": {
        "id": "text NOT NULL",
        "name": "text NOT NULL",
        "created_at": "timestamp with time zone NOT NULL",
        "slug": "text NOT NULL",
        "logo": "text",
        "metadata": "text",
    },
    "public.workspace_config": {
        "workspace_id": "text NOT NULL",
        "key": "text NOT NULL",
        "value": "text NOT NULL",
        "updated_at": "timestamp with time zone NOT NULL",
    },
}
