/**
 * So a whole-file edit of `CONCEPTS.md` cannot scrub a mark unseen. A head retired or renamed leaves
 * the list in the same change.
 */
export const INTERNAL_HEADS: readonly string[] = [
  "actor id",
  "admission",
  "answer contract",
  "api",
  "block",
  "boundary schema",
  "browsing role",
  "bundle commit",
  "bundle estate",
  "cascade",
  "claimant",
  "company language",
  "concept index",
  "concept write request",
  "consumer",
  "consumer-domain list",
  "converter",
  "cue",
  "dead-man ping",
  "deploy unit",
  "detail address",
  "detection key",
  "effective class",
  "emptying a connected source",
  "entity merge",
  "envelope",
  "erasure map",
  "erasure match",
  "erasure pseudonym",
  "erasure rehearsal",
  "escrow",
  "estate",
  "forge",
  "generation",
  "git store",
  "go-live",
  "governed write",
  "head check",
  "include",
  "issue word",
  "job",
  "journeys",
  "knowledge layer",
  "land (the verb)",
  "landed copy",
  "lease",
  "local database",
  "log line",
  "map sweep",
  "MCP surface",
  "menu group",
  "merge key",
  "minter",
  "minting",
  "model client",
  "operator",
  "outcome",
  "person id",
  "principal",
  "producer",
  "reconciler hit",
  "record family",
  "redaction seam",
  "refinement",
  "refused items",
  "release",
  "release mode",
  "replay copy",
  "restore drill",
  "root refusal",
  "route spec",
  "run key",
  "staging",
  "step (of an action)",
  "strand",
  "sweep pass",
  "tenant",
  "test inbox",
  "test person",
  "test workspace",
  "tier (of a backup)",
  "token scope",
  "top band",
  "`ui://`",
  "upload sweep",
  "view-state slot",
  "watermark",
  "window",
  "withholding",
  "written span",
];
