import { globSync, readFileSync } from "node:fs";
import path from "node:path";

import { is, SQL } from "drizzle-orm";
import { getTableConfig, PgDialect } from "drizzle-orm/pg-core";
import type pg from "pg";
import { describe, expect, it } from "vitest";

import {
  anyWordMatch,
  MARK_THE_MATCH_LEAKPROOF,
  passage,
  type MatchStrength,
} from "../src/index.ts";
import { testData } from "./factory.ts";
import { withRollback } from "./harness.ts";
import { matchIsLeakproof, postgresForSuite, refusesEach, UNMARK_THE_MATCH } from "./probes.ts";

const db = postgresForSuite();

const leakproofFunctions = async (client: pg.PoolClient): Promise<readonly string[]> => {
  const read = await client.query<{ signature: string }>(
    "SELECT oid::regprocedure::text AS signature FROM pg_catalog.pg_proc WHERE proleakproof ORDER BY 1",
  );
  return read.rows.map((row) => row.signature);
};

describe("the full-text match `find` filters a passage by", () => {
  it("is leakproof once migrated as a deploy migrates", async () => {
    await withRollback(db().pool, async (client) => {
      expect(await matchIsLeakproof(client)).toBe(true);
    });
  });

  it("is marked again after a restore, and twice changes nothing", async () => {
    await withRollback(db().pool, async (client) => {
      await client.query(UNMARK_THE_MATCH);
      const restored = await matchIsLeakproof(client);

      await client.query(MARK_THE_MATCH_LEAKPROOF);
      const marked = await matchIsLeakproof(client);
      await client.query(MARK_THE_MATCH_LEAKPROOF);

      expect({ restored, marked, again: await matchIsLeakproof(client) }).toEqual({
        restored: false,
        marked: true,
        again: true,
      });
    });
  });

  it("is the only function migrate's mark changes", async () => {
    await withRollback(db().pool, async (client) => {
      await client.query(UNMARK_THE_MATCH);
      const before = await leakproofFunctions(client);

      await client.query(MARK_THE_MATCH_LEAKPROOF);
      const after = await leakproofFunctions(client);

      expect({
        marked: after.filter((signature) => !before.includes(signature)),
        unmarked: before.filter((signature) => !after.includes(signature)),
      }).toEqual({ marked: ["ts_match_vq(tsvector,tsquery)"], unmarked: [] });
    });
  });

  it("is refused to both runtime roles, and the mark stands", async () => {
    await withRollback(db().pool, async (client) => {
      for (const role of ["app_rt", "worker_rt"]) {
        await client.query("RESET ROLE");
        await client.query(`SET LOCAL ROLE ${role}`);
        await refusesEach(client, [
          [MARK_THE_MATCH_LEAKPROOF, `${role} marking the match leakproof`, [], /must be owner/],
          [UNMARK_THE_MATCH, `${role} taking the mark off the match`, [], /must be owner/],
        ]);
      }
      await client.query("RESET ROLE");

      expect(await matchIsLeakproof(client)).toBe(true);
    });
  });
});

const REPO_ROOT = path.resolve(import.meta.dirname, "../../..");

const THE_RULE = "packages/schema/src/full-text-match.ts";

const LANGUAGE_IN_QUOTES = /(["'`])english\1/i;

/** A call with no configuration falls back to the server's default, which can differ from ours. */
const CALL_WITHOUT_THE_LANGUAGE =
  /\b(?:to_tsvector|to_tsquery|plainto_tsquery|phraseto_tsquery|websearch_to_tsquery)\s*\((?!\s*\$\{FULL_TEXT_LANGUAGE\})/i;

const choosesItsOwnLanguage = (text: string): boolean =>
  LANGUAGE_IN_QUOTES.test(text) || CALL_WITHOUT_THE_LANGUAGE.test(text);

const sourceFiles = (): readonly string[] =>
  globSync(["apps/*/src/**/*.{ts,tsx}", "packages/*/src/**/*.{ts,tsx}"], {
    cwd: REPO_ROOT,
    exclude: ["**/node_modules/**"],
  }).toSorted((a, b) => a.localeCompare(b));

/** The SQL the passage table's Drizzle definition gives its stored full-text column. */
const passageSearchExpression = (): { readonly sql: string; readonly params: unknown[] } => {
  const generated = getTableConfig(passage).columns.find((column) => column.name === "search")
    ?.generated?.as;
  if (!is(generated, SQL)) throw new Error("the passage's search column is not generated by SQL");
  return new PgDialect().sqlToQuery(generated);
};

describe("the full-text rule's SQL", () => {
  it("stores a passage's vector exactly as its migration wrote it", () => {
    expect(passageSearchExpression()).toEqual({
      sql: "to_tsvector('english', content)",
      params: [],
    });
  });
});

const BY_TITLE = anyWordMatch("c.search", "$2", ["c.title"]);

type Narrowed = {
  readonly strength?: MatchStrength;
  readonly after?: readonly [matched: number, rank: number, title: string];
};

type Matched = { readonly title: string; readonly matched: number; readonly rank: number };

/** Concept rows titled and bodied as given, read back by the rule over `text`, keyed by title. */
const matchedOver = (
  concepts: readonly (readonly [title: string, body: string])[],
  text: string,
  narrowed: Narrowed = {},
): Promise<readonly Matched[]> =>
  withRollback(db().pool, async (client) => {
    const seed = testData(client);
    const { id: workspaceId } = await seed.workspace();
    for (const [title, body] of concepts) await seed.conceptIndex({ workspaceId, title, body });
    const { strength, after } = narrowed;
    const read = await client.query<Matched>(
      `SELECT c.title, ${BY_TITLE.columns}
         FROM concept_index c
         ${BY_TITLE.joins}
        WHERE c.workspace_id = $1
          AND ${BY_TITLE.matches}
          ${strength === undefined ? "" : `AND ${BY_TITLE.strength(strength)}`}
          ${after === undefined ? "" : `AND ${BY_TITLE.after({ matched: "$3", rank: "$4", key: ["$5"] })}`}
        ORDER BY ${BY_TITLE.order}`,
      [workspaceId, text, ...(after ?? [])],
    );
    return read.rows;
  });

const UNRELATED = "Nothing here bears on it.";

describe("the any-word rule over concept rows", () => {
  it("matches a row holding any one of the text's words", async () => {
    const matched = await matchedOver(
      [
        ["Audit Logs Retention", UNRELATED],
        ["Retention", UNRELATED],
        ["Holiday policy", UNRELATED],
      ],
      "audit log retention",
    );

    expect(matched.map(({ title }) => title)).toEqual(["Audit Logs Retention", "Retention"]);
  });

  it("ranks distinct words held, then density, then key", async () => {
    const matched = await matchedOver(
      [
        ["Logs", "audit audit audit audit audit audit"],
        ["Audit Logs Retention", UNRELATED],
        ["Audit", UNRELATED],
        ["Log", UNRELATED],
      ],
      "audit log retention",
    );

    expect(matched).toEqual([
      { title: "Audit Logs Retention", matched: 3, rank: 3 },
      { title: "Logs", matched: 2, rank: 2.200000047683716 },
      { title: "Audit", matched: 1, rank: 1 },
      { title: "Log", matched: 1, rank: 1 },
    ]);
  });

  it("holds a strong match to half the words, rounded up", async () => {
    const concepts = [
      ["Audit", UNRELATED],
      ["Audit Logs", UNRELATED],
      ["Audit Logs Retention", UNRELATED],
    ] as const;

    const titles = async (text: string, strength: MatchStrength) =>
      (await matchedOver(concepts, text, { strength })).map(({ title }) => title);

    expect({
      threeStrong: await titles("audit log retention", "strong"),
      threeWeak: await titles("audit log retention", "weak"),
      fourStrong: await titles("audit log retention policy", "strong"),
      fourWeak: await titles("audit log retention policy", "weak"),
    }).toEqual({
      threeStrong: ["Audit Logs Retention", "Audit Logs"],
      threeWeak: ["Audit"],
      fourStrong: ["Audit Logs Retention", "Audit Logs"],
      fourWeak: ["Audit"],
    });
  });

  it("continues after a bound by words held, rank, then key", async () => {
    const concepts = [
      ["Audit Logs", UNRELATED],
      ["Audit", "audit"],
      ["Log", "log"],
      ["Retention", UNRELATED],
    ] as const;

    const after = async (bound: NonNullable<Narrowed["after"]>) =>
      (await matchedOver(concepts, "audit log retention", { after: bound })).map(
        ({ title }) => title,
      );

    expect({
      pastTheTwoWordRow: await after([2, 2, "Audit Logs"]),
      pastTheDenserRow: await after([1, 1.2000000476837158, "Log"]),
      pastTheKey: await after([1, 1.2000000476837158, "Audit"]),
      pastTheLast: await after([1, 1, "Retention"]),
    }).toEqual({
      pastTheTwoWordRow: ["Audit", "Log", "Retention"],
      pastTheDenserRow: ["Retention"],
      pastTheKey: ["Log", "Retention"],
      pastTheLast: [],
    });
  });

  it.each([
    ["the largest bounds", Number.MAX_SAFE_INTEGER, Number.MAX_VALUE],
    ["the smallest rank", 0, Number.MIN_VALUE],
  ])("compares a bound of %s without error", async (_case, matched, rank) => {
    const after = await matchedOver([["Audit", UNRELATED]], "audit", {
      after: [matched, rank, "Audit"],
    });

    expect(after.map(({ title }) => title)).toEqual(matched === 0 ? [] : ["Audit"]);
  });

  it("reads `!`, `:*`, `&`, quotes and parentheses as no syntax", async () => {
    const matched = await matchedOver(
      [
        ["Audit Logs", UNRELATED],
        ["O'Brien", UNRELATED],
        ["Holiday policy", UNRELATED],
      ],
      String.raw`!audit:* & (log | 'o''brien \ "`,
    );

    expect(matched.map(({ title }) => title)).toEqual(["Audit Logs", "O'Brien"]);
  });

  it("matches a word whose parsed form keeps a quote", async () => {
    const matched = await matchedOver(
      [
        ["See example.com/o'brien", UNRELATED],
        ["Holiday policy", UNRELATED],
      ],
      "example.com/o'brien",
    );

    expect(matched).toEqual([{ title: "See example.com/o'brien", matched: 3, rank: 3 }]);
  });

  it("matches nothing on stop words alone, and raises nothing", async () => {
    const matched = await matchedOver([["The policy", "It is what it is."]], "the and of it is");

    expect(matched).toEqual([]);
  });
});

describe("the language every full-text match is parsed under", () => {
  it("is chosen in source only by the full-text rule", () => {
    const choosing = sourceFiles().filter(
      (file) =>
        file !== THE_RULE &&
        choosesItsOwnLanguage(readFileSync(path.join(REPO_ROOT, file), "utf8")),
    );

    expect(choosing).toEqual([]);
  });

  it("is looked for in the files that match text", () => {
    const read = sourceFiles();

    expect(
      [THE_RULE, "packages/core/src/sources/passages.ts"].filter((file) => !read.includes(file)),
    ).toEqual([]);
  });

  it("is refused when a query leaves it to the server", () => {
    expect(choosesItsOwnLanguage("CROSS JOIN websearch_to_tsquery($2) AS q")).toBe(true);
  });

  it("is refused however the call's name is spelled", () => {
    expect(
      ["WEBSEARCH_TO_TSQUERY($2)", "to_tsquery ($2)"].filter(choosesItsOwnLanguage),
    ).toHaveLength(2);
  });

  it("is refused when a call names another configuration", () => {
    expect(choosesItsOwnLanguage("to_tsvector('simple', body)")).toBe(true);
  });

  it("is refused when written in quotes in any case", () => {
    expect(choosesItsOwnLanguage(`const language = "English";`)).toBe(true);
  });

  it("passes in prose, and in a call that takes it", () => {
    expect(
      [
        " * English for the compare-and-swap match below.",
        `SELECT plainto_tsquery(\${FULL_TEXT_LANGUAGE}, word) AS probe`,
        `SELECT to_tsvector(\n  \${FULL_TEXT_LANGUAGE},\n  content\n)`,
      ].filter(choosesItsOwnLanguage),
    ).toEqual([]);
  });
});
