import { globSync, readFileSync } from "node:fs";
import path from "node:path";

import { is, SQL } from "drizzle-orm";
import { getTableConfig, PgDialect } from "drizzle-orm/pg-core";
import type pg from "pg";
import { describe, expect, it } from "vitest";

import { fullTextQuery, MARK_THE_MATCH_LEAKPROOF, passage } from "../src/index.ts";
import { withRollback } from "./harness.ts";
import { matchIsLeakproof, postgresForSuite, refusesEach, UNMARK_THE_MATCH } from "./probes.ts";

const db = postgresForSuite();

const leakproofFunctions = async (client: pg.PoolClient): Promise<readonly string[]> => {
  const read = await client.query<{ signature: string }>(
    "SELECT oid::regprocedure::text AS signature FROM pg_catalog.pg_proc WHERE proleakproof ORDER BY 1",
  );
  return read.rows.map((row) => row.signature);
};

describe("the full-text match `find` filters a passage by", () => {
  it("is leakproof once migrated as a deploy migrates", async () => {
    await withRollback(db().pool, async (client) => {
      expect(await matchIsLeakproof(client)).toBe(true);
    });
  });

  it("is marked again after a restore, and twice changes nothing", async () => {
    await withRollback(db().pool, async (client) => {
      await client.query(UNMARK_THE_MATCH);
      const restored = await matchIsLeakproof(client);

      await client.query(MARK_THE_MATCH_LEAKPROOF);
      const marked = await matchIsLeakproof(client);
      await client.query(MARK_THE_MATCH_LEAKPROOF);

      expect({ restored, marked, again: await matchIsLeakproof(client) }).toEqual({
        restored: false,
        marked: true,
        again: true,
      });
    });
  });

  it("is the only function migrate's mark changes", async () => {
    await withRollback(db().pool, async (client) => {
      await client.query(UNMARK_THE_MATCH);
      const before = await leakproofFunctions(client);

      await client.query(MARK_THE_MATCH_LEAKPROOF);
      const after = await leakproofFunctions(client);

      expect({
        marked: after.filter((signature) => !before.includes(signature)),
        unmarked: before.filter((signature) => !after.includes(signature)),
      }).toEqual({ marked: ["ts_match_vq(tsvector,tsquery)"], unmarked: [] });
    });
  });

  it("is refused to both runtime roles, and the mark stands", async () => {
    await withRollback(db().pool, async (client) => {
      for (const role of ["app_rt", "worker_rt"]) {
        await client.query("RESET ROLE");
        await client.query(`SET LOCAL ROLE ${role}`);
        await refusesEach(client, [
          [MARK_THE_MATCH_LEAKPROOF, `${role} marking the match leakproof`, [], /must be owner/],
          [UNMARK_THE_MATCH, `${role} taking the mark off the match`, [], /must be owner/],
        ]);
      }
      await client.query("RESET ROLE");

      expect(await matchIsLeakproof(client)).toBe(true);
    });
  });
});

const REPO_ROOT = path.resolve(import.meta.dirname, "../../..");

const THE_RULE = "packages/schema/src/full-text-match.ts";

const LANGUAGE_IN_QUOTES = /(["'`])english\1/i;

/** A call with no configuration falls back to the server's default, which can differ from ours. */
const CALL_WITHOUT_THE_LANGUAGE =
  /\b(?:to_tsvector|to_tsquery|plainto_tsquery|phraseto_tsquery|websearch_to_tsquery)\(\s*(?!\$\{FULL_TEXT_LANGUAGE\})/;

const choosesItsOwnLanguage = (text: string): boolean =>
  LANGUAGE_IN_QUOTES.test(text) || CALL_WITHOUT_THE_LANGUAGE.test(text);

const sourceFiles = (): readonly string[] =>
  globSync(["apps/*/src/**/*.{ts,tsx}", "packages/*/src/**/*.{ts,tsx}"], {
    cwd: REPO_ROOT,
    exclude: ["**/node_modules/**"],
  }).toSorted((a, b) => a.localeCompare(b));

/** The SQL the passage table's Drizzle definition gives its stored full-text column. */
const passageSearchExpression = (): { readonly sql: string; readonly params: unknown[] } => {
  const generated = getTableConfig(passage).columns.find((column) => column.name === "search")
    ?.generated?.as;
  if (!is(generated, SQL)) throw new Error("the passage's search column is not generated by SQL");
  return new PgDialect().sqlToQuery(generated);
};

describe("the full-text rule's SQL", () => {
  it("stores a passage's vector exactly as its migration wrote it", () => {
    expect(passageSearchExpression()).toEqual({
      sql: "to_tsvector('english', content)",
      params: [],
    });
  });

  it("parses a query as passage search always has", () => {
    expect(fullTextQuery("$2")).toBe("websearch_to_tsquery('english', $2)");
  });
});

describe("the language every full-text match is parsed under", () => {
  it("is chosen in source only by the full-text rule", () => {
    const choosing = sourceFiles().filter(
      (file) =>
        file !== THE_RULE &&
        choosesItsOwnLanguage(readFileSync(path.join(REPO_ROOT, file), "utf8")),
    );

    expect(choosing).toEqual([]);
  });

  it("is looked for in the files that match text", () => {
    const read = sourceFiles();

    expect(
      [THE_RULE, "packages/core/src/sources/passages.ts"].filter((file) => !read.includes(file)),
    ).toEqual([]);
  });

  it("is refused when a query leaves it to the server", () => {
    expect(choosesItsOwnLanguage("CROSS JOIN websearch_to_tsquery($2) AS q")).toBe(true);
  });

  it("is refused when a call names another configuration", () => {
    expect(choosesItsOwnLanguage("to_tsvector('simple', body)")).toBe(true);
  });

  it("is refused when written in quotes in any case", () => {
    expect(choosesItsOwnLanguage(`const language = "English";`)).toBe(true);
  });

  it("passes in prose, and in a call that takes it", () => {
    expect(
      [
        " * English for the compare-and-swap match below.",
        `SELECT plainto_tsquery(\${FULL_TEXT_LANGUAGE}, word) AS probe`,
      ].filter(choosesItsOwnLanguage),
    ).toEqual([]);
  });
});
