"""The one memoised function: a landed copy converted, redacted and cut into chunks
(`[TEST1]`, `[TEST3]`, `[TEST7]`, `[TEST9]`).

Driven through `better_answers_worker.pipeline`'s own interface, over a real engine and
a real detector, because everything these cases are about is what the memo does between
two runs — and a memo nobody ran is a decoration.

**No database.** Nothing here writes a row: the memo lives in the binding's store on
disk and the chunk rows are the wave after this one. The pool a run would use is built
lazily and never asked for, which is why the bootstrap below names an address that does
not answer — a case that quietly opened a connection would fail there rather than pass
here.

**The object store is the one external service, and it is replaced behind its adapter**
with the dictionary below (`[TEST3]`). The bytes of a landed copy are what the estate's
bucket would hand back; what the cases are about is which key they were asked for and
which key the normalised copy went under, and a bucket cannot say that more clearly than
a dictionary can.

**The converters are real and so are their documents.** `anydoc` and `pdf-inspector` run
here exactly as they run in the image, over the committed fixtures in
`tests/fixtures/conversion/` — because what a converter makes of a real `.docx` or a
real PDF is the whole question, and a document a case generated would be a document
generated by whichever writer the case imported. The first act that proved both of them
*on the worker image, under the engine's runtime* is the case named
`test_both_converters_hold_on_the_image_under_the_engines_own_runtime` in
`tests/test_image.py`, whose docblock carries its four readings and the memory beside
them.

**What is written down here, and why it is not derived.** The redacted text of every
document, the categories the seam raises, the version string and every chunk boundary
are literals (`[TEST9]`). The two markdown documents' were read out of the seam on 11
September 2026 at `rule_version` 1 and the converted fixtures' on 20 September 2026 at
`rule_version` 2, each at the detector pin this tier ships; a case that asked the seam
or the converter what it answered would agree with either answering anything.
"""

from collections.abc import Iterator, Mapping, Sequence
from inspect import signature
from pathlib import Path
from typing import get_args

import pytest

from better_answers_worker.pipeline import (
    CONVERTER_PIN,
    DOCX_MEDIA_TYPE,
    MEMO_VERSION,
    OCR_ANSWER,
    PDF_MEDIA_TYPE,
    SEAM_MS_PER_PAGE,
    TIMEOUT_MARGIN_MS,
    Chunk,
    Host,
    IndexRun,
    LandedDocument,
    LandedRun,
    Suppression,
    converted,
    converter_pin_of,
    object_key_of,
    pages_of,
    redact_landed_copies,
    suppression_of,
    timeout_for,
)
from better_answers_worker.redaction.pins import DETECTOR_PIN, RULE_VERSION
from test_pipeline_host import bootstrap_for

WORKSPACE = "01M2Q3R4S5T6V7W8X9YZAB0000"
BINDING = "01M2B1ND1NGAAAAAAAAAAAAAAA"

#: A binding nobody configured — the shape the `source_binding` column takes by default,
#: under which the always tier is written out of the text and a name is left in it.
THE_SAFE_SET: Mapping[str, bool] = {"default_on": True, "default_off": False}

#: One binding's own seed, from which a name's letter is drawn. Spelled rather than
#: generated: a seed that moved between two runs would re-read every document, which is
#: the very thing the second case says must not happen.
SEED = "b0f3a1d2c4e5"

#: An invoice carrying a sort code beside an account number, which the seam raises as
#: one `bank-details` span at the tier no binding can switch off (ADR 0027: every value
#: invented). Its account number is the string the memo must never be found holding.
AN_INVOICE_ID = "01M2Q3R4S5T6V7W8X9YZAB0001"
AN_INVOICE = (
    "Invoice 2026-041 is due on receipt.\n\n"
    "The sort code is 20-00-00 and the account number is 12345678.\n\n"
    "Delivery follows within ten working days of a signed order.\n"
)
AN_INVOICE_REDACTED = (
    "Invoice 2026-041 is due on receipt.\n\n"
    "The sort code is [withheld].\n\n"
    "Delivery follows within ten working days of a signed order.\n"
)
THE_ACCOUNT_NUMBER = "12345678"

#: A delivery note naming one person. Under the safe set a name is a **finding** and not
#: a withholding, so this document's redacted text is its own text — until an erasure
#: request names her, which raises her span to the always tier and writes her out. That
#: is what makes this the document the suppression case moves, and the invoice the one
#: it must leave alone.
A_DELIVERY_NOTE_ID = "01M2Q3R4S5T6V7W8X9YZAB0002"
A_DELIVERY_NOTE = (
    "Deliveries are booked by Priya Raman on 0161 496 0000.\n\n"
    "The depot opens at seven.\n"
)
A_DELIVERY_NOTE_SUPPRESSED = (
    "Deliveries are booked by [withheld] on 0161 496 0000.\n\n"
    "The depot opens at seven.\n"
)

#: The erasure request that reaches the delivery note, as the `subject_request` row
#: holds its identifier set: identifiers by the kind each was given under.
HER_ERASURE_REQUEST = suppression_of(
    {"name": ("Priya Raman",), "email": ("priya.raman@example.test",)}
)

CONTRACTS = Path(__file__).resolve().parents[3] / "contracts"

#: The four fixtures the converter's cases read, one per road through it. They are
#: committed bytes rather than files a case writes, because what is under test is what
#: `anydoc` and `pdf-inspector` make of a real `.docx` and a real PDF — and a document
#: this suite generated would be a document generated by whichever writer it imported.
#: `tests/fixtures/conversion/README.md` says how each was made and what it holds.
CONVERSION_FIXTURES = Path(__file__).resolve().parent / "fixtures" / "conversion"

#: The `.docx`: a heading, a paragraph, a bank-details sentence, a bulleted list and a
#: two-column table. One fixture proves the whole road for its type — converted to
#: Markdown, redacted by the seam, cut into chunks.
A_POLICY_ID = "01M2Q3R4S5T6V7W8X9YZAB0003"
A_POLICY_CONVERTED = (
    "# Expenses policy\n\n"
    "Claims are paid monthly.\n\n"
    "The sort code is 20-00-00 and the account number is 12345678.\n\n"
    "- Keep receipts\n"
    "- Submit by the fifth\n\n"
    "| Item | Limit |\n"
    "| --- | --- |\n"
    "| Hotel | 120 |\n"
    "| Mileage | 45p |\n"
)
A_POLICY_REDACTED = (
    "# Expenses policy\n\n"
    "Claims are paid monthly.\n\n"
    "The sort code is [withheld].\n\n"
    "- Keep receipts\n"
    "- Submit by the fifth\n\n"
    "| Item | Limit |\n"
    "| --- | --- |\n"
    "| Hotel | 120 |\n"
    "| Mileage | 45p |\n"
)

#: The PDF with a text layer: a heading, a sentence and a three-row table. It carries
#: nothing the seam withholds, so its redacted text is its converted text — which is
#: what makes it the fixture the Markdown table is read off.
A_RATE_CARD_ID = "01M2Q3R4S5T6V7W8X9YZAB0004"
A_RATE_CARD_CONVERTED = (
    "# Rate card\n\n"
    "## Rates hold for the quarter.\n\n"
    "|Service|Day rate|\n"
    "|---|---|\n"
    "|Survey|450|\n"
    "|Report|300|\n"
)

#: The plain-text fixture: a supplier's delivery terms, long enough to be cut into more
#: than one chunk, carrying the same bank-details sentence the other two do. Plain text
#: needs no converter at all — its bytes *are* the normalised text — so what this one
#: proves is that the road is the same road for a type nothing converts: the seam reads
#: the file, the splitter reads what the seam left, and a locator's offsets are offsets
#: into the uploaded file.
A_TERMS_ID = "01M2Q3R4S5T6V7W8X9YZAB0007"
A_TERMS_REDACTED = (
    "Delivery terms for the Northgate depot.\n"
    "\n"
    "Orders received before eleven in the morning are picked the same working day.\n"
    "Anything later is picked the next. The depot does not pick on a Saturday and the\n"
    "gate is locked from noon.\n"
    "\n"
    "Pallets are counted in and counted out. A short delivery is raised on the day it\n"
    "is noticed and never at the end of the month, because a pallet nobody counted is\n"
    "a pallet nobody can find.\n"
    "\n"
    "Payment is thirty days from the end of the month in which the invoice falls. The\n"
    "sort code is [withheld]. Remittance advice goes\n"
    "to the accounts inbox and not to the depot.\n"
    "\n"
    "Returns are accepted within fourteen days on the original pallet. A pallet that\n"
    "arrives broken is photographed before it is unloaded, and the photograph is the\n"
    "record the claim rests on.\n"
    "\n"
    "Fuel is charged at cost and reviewed each quarter. A change to the rate is given\n"
    "in writing one full month before it takes effect, so that a quotation already\n"
    "given holds to the price it was given at.\n"
    "\n"
    "Pallets left on site beyond the fourteen days are collected on the next run to\n"
    "the depot and charged at the standing rate. A pallet the driver cannot reach is\n"
    "not a pallet the driver collected, and the note says so.\n"
    "\n"
    "These terms hold for the length of the agreement and are read with the schedule\n"
    "rather than instead of it.\n"
)

#: The PDF with no text layer at all — one page drawn as a bitmap. `pdf-inspector`
#: answers it as a page needing OCR, which quarantines the document whole.
A_SCAN_ID = "01M2Q3R4S5T6V7W8X9YZAB0005"

#: A `.docx` that is not one: the first four hundred bytes of the fixture's zip, which
#: is the shape a truncated upload takes. `anydoc` raises over it by name.
A_TRUNCATED_ID = "01M2Q3R4S5T6V7W8X9YZAB0006"


def fixture_bytes(name: str) -> bytes:
    return (CONVERSION_FIXTURES / name).read_bytes()


class ABucket:
    """The estate's object store, as a dictionary of the bytes under each key.

    It is the adapter's own interface and not boto3's: what the cases need to see is
    which key was read, which key was written and how many times — and a real bucket
    would answer those questions no better and a great deal more slowly (`[TEST3]`).
    """

    def __init__(self, objects: Mapping[str, bytes]) -> None:
        self.objects = dict(objects)
        self.reads: list[str] = []
        self.writes: list[str] = []

    def read(self, key: str) -> bytes:
        self.reads.append(key)
        return self.objects[key]

    def write(self, key: str, body: bytes) -> None:
        self.writes.append(key)
        self.objects[key] = body


def a_landed_document(
    document_id: str,
    *,
    media_type: str = "text/markdown",
    suppressions: Sequence[Suppression] = (),
) -> LandedDocument:
    """One document as its catalogue row addresses it, with the bind act's two keys."""
    return LandedDocument(
        source_document_id=document_id,
        media_type=media_type,
        original_key=f"documents/{document_id.lower()}/original",
        normalised_key=f"documents/{document_id.lower()}/normalised",
        suppressions=tuple(suppressions),
    )


THE_INVOICE = a_landed_document(AN_INVOICE_ID)
THE_DELIVERY_NOTE = a_landed_document(A_DELIVERY_NOTE_ID)


def a_bucket_holding_both() -> ABucket:
    return ABucket(
        {
            THE_INVOICE.original_key: AN_INVOICE.encode(),
            THE_DELIVERY_NOTE.original_key: A_DELIVERY_NOTE.encode(),
        }
    )


@pytest.fixture(name="host")
def a_host(tmp_path: Path) -> Iterator[Host]:
    """A host over a store of its own, and an address no connection is ever made to."""
    with Host(bootstrap_for("postgresql://unreached/unreached", tmp_path)) as opened:
        yield opened


def a_run(reason: str = "bound") -> IndexRun:
    return IndexRun(workspace_id=WORKSPACE, binding_id=BINDING, reason=reason)


def read_the_copies(
    host: Host,
    bucket: ABucket,
    documents: Sequence[LandedDocument],
    *,
    memo_version: str = MEMO_VERSION,
    ms_per_page: int = SEAM_MS_PER_PAGE,
    margin_ms: int = TIMEOUT_MARGIN_MS,
) -> LandedRun:
    return redact_landed_copies(
        host,
        a_run(),
        documents,
        bucket,
        THE_SAFE_SET,
        SEED,
        memo_version=memo_version,
        ms_per_page=ms_per_page,
        margin_ms=margin_ms,
    )


def quarantine_of(answer: LandedRun) -> dict[str, str]:
    """Which documents this run could not read, and what refused each of them."""
    return {
        document.source_document_id: document.error for document in answer.quarantined
    }


def text_of(answer: LandedRun, document_id: str) -> str:
    """The redacted text this run read for one document."""
    return next(
        document.redacted.text
        for document in answer.documents
        if document.source_document_id == document_id
    )


# -- the memoised function -------------------------------------------------------------


def test_a_landed_copy_comes_back_with_what_its_binding_withholds_written_out_of_it(
    host: Host,
) -> None:
    """The memoised body is the conversion and then the seam, in that order and in
    one function, so the only text the memo is ever handed to hold is the redacted
    one.
    """
    bucket = a_bucket_holding_both()

    answer = read_the_copies(host, bucket, (THE_INVOICE,))

    assert text_of(answer, AN_INVOICE_ID) == AN_INVOICE_REDACTED
    assert answer.documents[0].redacted.verdict is None
    assert dict(answer.documents[0].redacted.counts) == {"bank-details": 1}
    assert answer.documents[0].redacted.version == f"{RULE_VERSION}:{DETECTOR_PIN}"


def test_the_bindings_store_is_never_found_holding_a_span_the_seam_withheld(
    host: Host,
) -> None:
    """ADR 0020's line, read off the disk it is about. Conversion sits inside the
    memoised function precisely so that no entry can hold the text as it arrived; a
    design that memoised the conversion separately would leave the account number below
    on a volume that is never backed up and never reviewed.
    """
    bucket = a_bucket_holding_both()

    read_the_copies(host, bucket, (THE_INVOICE,))

    held = b"".join(
        path.read_bytes()
        for path in sorted(host.binding_directory(a_run()).rglob("*"))
        if path.is_file()
    )
    assert b"[withheld]" in held, "the redacted text is what the memo is for"
    assert THE_ACCOUNT_NUMBER.encode() not in held
    assert b"20-00-00" not in held


def test_a_second_run_over_an_unchanged_document_reads_nothing_afresh(
    host: Host,
) -> None:
    """The whole point of the memo: the detector is the expensive thing in this tier,
    and a binding re-indexed for a reason that touched no document must not run it
    again.
    """
    bucket = a_bucket_holding_both()
    both = (THE_INVOICE, THE_DELIVERY_NOTE)

    first = read_the_copies(host, bucket, both)
    again = read_the_copies(host, bucket, both)

    assert first.read_afresh == 2
    assert again.read_afresh == 0
    assert text_of(again, AN_INVOICE_ID) == AN_INVOICE_REDACTED
    assert text_of(again, A_DELIVERY_NOTE_ID) == A_DELIVERY_NOTE


def test_a_suppression_on_one_document_re_reads_that_document_and_no_other(
    host: Host,
) -> None:
    """The reason the suppressions are an argument and never a change key: a key would
    put the whole binding's memo out of date the day one person asked to be erased, and
    the next run would re-read every document in it to answer for one.
    """
    bucket = a_bucket_holding_both()
    before = (THE_INVOICE, THE_DELIVERY_NOTE)
    after = (
        THE_INVOICE,
        a_landed_document(A_DELIVERY_NOTE_ID, suppressions=(HER_ERASURE_REQUEST,)),
    )

    read_the_copies(host, bucket, before)
    answer = read_the_copies(host, bucket, after)

    assert answer.read_afresh == 1
    assert text_of(answer, A_DELIVERY_NOTE_ID) == A_DELIVERY_NOTE_SUPPRESSED
    assert text_of(answer, AN_INVOICE_ID) == AN_INVOICE_REDACTED


def test_a_run_under_a_moved_detector_pin_reads_every_document_afresh(
    host: Host,
) -> None:
    """The other half of the pair (`[TEST7]`): the suppression moves one document's key
    and the version moves all of them, because a span the detector would read
    differently today is a span every offset in the binding rests on.
    """
    bucket = a_bucket_holding_both()
    both = (THE_INVOICE, THE_DELIVERY_NOTE)

    read_the_copies(host, bucket, both)
    answer = read_the_copies(host, bucket, both, memo_version="2:a-later-detector")

    assert answer.read_afresh == 2


def test_the_memo_is_versioned_by_the_seams_own_rule_version_and_detector_pin() -> None:
    """Written down rather than read off the pins (`[TEST9]`): the two halves joined
    by a colon is the string the finding rows and the document's own column carry, and a
    memo versioned by anything less would survive a detector the evidence no longer
    rests on. The converters are joined to it by the case further down, and for the same
    reason.
    """
    assert MEMO_VERSION.startswith(f"{RULE_VERSION}:{DETECTOR_PIN}")
    assert MEMO_VERSION.startswith("2:presidio-2.2.364+gliner-0.2.29+torch-2.14.0+")


# -- the two copies --------------------------------------------------------------------


def test_the_normalised_redacted_text_lands_under_the_documents_normalised_key(
    host: Host,
) -> None:
    bucket = a_bucket_holding_both()

    read_the_copies(host, bucket, (THE_INVOICE,))

    assert bucket.writes == [THE_INVOICE.normalised_key]
    assert bucket.objects[THE_INVOICE.normalised_key] == AN_INVOICE_REDACTED.encode()


def test_the_original_landed_copy_is_read_and_never_written(host: Host) -> None:
    """The original is the evidence an erasure map is read from and a re-detection is
    re-run over, so a run that wrote over it would destroy the only thing that could
    answer what a document said before the seam saw it.
    """
    bucket = a_bucket_holding_both()

    read_the_copies(host, bucket, (THE_INVOICE,))

    assert bucket.reads == [THE_INVOICE.original_key]
    assert THE_INVOICE.original_key not in bucket.writes
    assert bucket.objects[THE_INVOICE.original_key] == AN_INVOICE.encode()


def test_a_landed_copy_is_reached_under_the_workspaces_own_prefix() -> None:
    """The catalogue's key is a key *inside* the workspace's prefix — the app's object
    door puts every one of its reads and writes under `workspaces/<id>/` and stores what
    is left. A worker that asked the bucket for the column's value alone would find
    nothing there, and would find it silently.
    """
    assert (
        object_key_of(WORKSPACE, "documents/01m2q3r4s5t6v7w8x9yzab0001/original")
        == "workspaces/01M2Q3R4S5T6V7W8X9YZAB0000"
        "/documents/01m2q3r4s5t6v7w8x9yzab0001/original"
    )


# -- the converter ---------------------------------------------------------------------


@pytest.mark.parametrize("media_type", ["text/markdown", "text/plain"])
def test_markdown_and_plain_text_pass_through_as_the_normalised_text(
    host: Host, media_type: str
) -> None:
    """Two of the four types the upload allow-list admits need no conversion at all:
    the bytes are the normalised text already, so the offsets a locator carries are
    offsets into what the reader uploaded. The other two go through a converter apiece
    — `anydoc` for `.docx`, `pdf-inspector` for PDF — in the cases below.
    """
    document = a_landed_document(AN_INVOICE_ID, media_type=media_type)
    bucket = ABucket({document.original_key: AN_INVOICE.encode()})

    answer = read_the_copies(host, bucket, (document,))

    assert text_of(answer, AN_INVOICE_ID) == AN_INVOICE_REDACTED


def test_plain_text_lands_as_its_own_bytes_redacted_and_cut_into_more_than_one_chunk(
    host: Host,
) -> None:
    """The pass-through road, held on a document of its own rather than on the string
    two cases share above. *Pass through* is a claim about bytes: what the seam is
    handed is the file exactly as the reader uploaded it, so a locator's offsets are
    offsets into that file and not into anything this tier wrote.

    This fixture is the only one long enough to be cut in two, which is what makes it
    the one the chunking is proved on: the rows rejoin to the redacted text with nothing
    added and nothing lost between them, and the second row's offsets carry on from
    where the first one stopped.
    """
    terms = a_landed_document(A_TERMS_ID, media_type="text/plain")
    bucket = ABucket({terms.original_key: fixture_bytes("delivery-terms.txt")})

    answer = read_the_copies(host, bucket, (terms,))
    chunks = answer.documents[0].chunks

    assert text_of(answer, A_TERMS_ID) == A_TERMS_REDACTED
    assert THE_ACCOUNT_NUMBER not in text_of(answer, A_TERMS_ID)
    assert bucket.objects[terms.normalised_key] == A_TERMS_REDACTED.encode()
    assert len(chunks) == 2
    assert "".join(chunk.content for chunk in chunks) == A_TERMS_REDACTED
    assert [chunk.id for chunk in chunks] == [
        f"{A_TERMS_ID}#000000",
        f"{A_TERMS_ID}#000001",
    ]
    assert chunks[1].char_start == chunks[0].char_end


def test_a_docx_converts_to_markdown_with_its_table_and_the_seam_reads_what_it_wrote(
    host: Host,
) -> None:
    """`anydoc`'s Markdown is what the seam is handed and what a locator addresses, so
    this case holds the whole road for the type: the heading, the list and the table
    survive as Markdown, and the bank-details sentence in the middle of them is the one
    thing the seam takes out.

    The redacted text is a literal read off the seam on 20 September 2026 at
    `rule_version` 2 and this tier's detector pin (`[TEST9]`); a case that asked the
    converter what it converted would agree with a converter that answered anything.
    """
    policy = a_landed_document(A_POLICY_ID, media_type=DOCX_MEDIA_TYPE)
    bucket = ABucket({policy.original_key: fixture_bytes("expenses-policy.docx")})

    answer = read_the_copies(host, bucket, (policy,))

    assert text_of(answer, A_POLICY_ID) == A_POLICY_REDACTED
    assert "| Hotel | 120 |" in text_of(answer, A_POLICY_ID)
    assert THE_ACCOUNT_NUMBER not in text_of(answer, A_POLICY_ID)
    assert bucket.objects[policy.normalised_key] == A_POLICY_REDACTED.encode()
    # And the flow cuts chunks out of that text, which is the far end of the road: the
    # converter's Markdown is what a locator's offsets are counted into.
    assert "".join(chunk.content for chunk in answer.documents[0].chunks) == (
        A_POLICY_REDACTED
    )
    assert answer.documents[0].chunks[0].id == f"{A_POLICY_ID}#000000"


def test_a_pdf_converts_to_markdown_with_its_table(host: Host) -> None:
    """PDF is `pdf-inspector`'s alone, and a table is the thing a full-text search would
    lose if the converter flattened it to one cell a line. This fixture carries nothing
    the seam withholds, so what lands under the normalised key is the converted text
    itself — which is what makes it the one the Markdown table is read off.
    """
    rate_card = a_landed_document(A_RATE_CARD_ID, media_type=PDF_MEDIA_TYPE)
    bucket = ABucket({rate_card.original_key: fixture_bytes("rate-card.pdf")})

    answer = read_the_copies(host, bucket, (rate_card,))

    assert text_of(answer, A_RATE_CARD_ID) == A_RATE_CARD_CONVERTED
    assert "|Survey|450|" in text_of(answer, A_RATE_CARD_ID)
    assert "".join(chunk.content for chunk in answer.documents[0].chunks) == (
        A_RATE_CARD_CONVERTED
    )


def test_a_pdf_with_a_page_that_has_no_text_layer_is_quarantined_whole(
    host: Host,
) -> None:
    """Whole, and never half-converted: a document with the scanned pages missing would
    be an address space with a hole in it, and every citation into the pages that did
    convert would point into a document nobody can see the whole of.

    The name is the converter's own, because an Admin deciding whether the binding needs
    OCR has to be able to tell a scan from a corrupt upload — and that share is the
    trigger that replaced docling's (ADR 0013, amended 20/09/2026).
    """
    scan = a_landed_document(A_SCAN_ID, media_type=PDF_MEDIA_TYPE)
    bucket = ABucket(
        {
            scan.original_key: fixture_bytes("scanned-invoice.pdf"),
            THE_DELIVERY_NOTE.original_key: A_DELIVERY_NOTE.encode(),
        }
    )

    answer = read_the_copies(host, bucket, (scan, THE_DELIVERY_NOTE))

    assert quarantine_of(answer) == {A_SCAN_ID: "NeedsOcrError"}
    assert [document.source_document_id for document in answer.documents] == [
        A_DELIVERY_NOTE_ID
    ]
    assert bucket.writes == [THE_DELIVERY_NOTE.normalised_key]


def test_a_document_the_converter_cannot_read_takes_no_neighbour_with_it(
    host: Host,
) -> None:
    """Per-document isolation, which is the whole reason the documents are fanned one
    component each. A truncated upload is refused by name inside its own component, the
    run goes on, its neighbour is read and lands, and the document the run could not
    read comes back on the run's own answer rather than as an exception — an exception
    here would make one unreadable upload the whole binding's failure.
    """
    truncated = a_landed_document(A_TRUNCATED_ID, media_type=DOCX_MEDIA_TYPE)
    bucket = ABucket(
        {
            truncated.original_key: fixture_bytes("expenses-policy.docx")[:400],
            THE_DELIVERY_NOTE.original_key: A_DELIVERY_NOTE.encode(),
        }
    )

    answer = read_the_copies(host, bucket, (truncated, THE_DELIVERY_NOTE))

    assert list(quarantine_of(answer)) == [A_TRUNCATED_ID]
    assert quarantine_of(answer)[A_TRUNCATED_ID] != ""
    assert text_of(answer, A_DELIVERY_NOTE_ID) == A_DELIVERY_NOTE
    assert bucket.writes == [THE_DELIVERY_NOTE.normalised_key]


def test_a_media_type_outside_the_allow_list_is_quarantined_and_never_guessed_at(
    host: Host,
) -> None:
    """The four types above are the whole of what this tier converts. A fifth is a
    document nothing here can read, and it is quarantined under that name rather than
    handed to whichever converter its bytes happen to resemble — a media type has one
    converter, and a type with none has none.
    """
    spreadsheet = a_landed_document(A_TRUNCATED_ID, media_type="application/zip")
    bucket = ABucket({spreadsheet.original_key: fixture_bytes("expenses-policy.docx")})

    answer = read_the_copies(host, bucket, (spreadsheet,))

    assert quarantine_of(answer) == {A_TRUNCATED_ID: "UnsupportedMediaType"}
    assert answer.documents == ()


def test_anydoc_is_told_to_reject_ocr_so_no_unredacted_byte_leaves_the_worker(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """ADR 0020's line applied to the converter. Conversion runs **before** the seam, so
    its input is the document exactly as the reader uploaded it — and under `anydoc`'s
    other arm, `"hosted"`, the library posts those bytes to `api.firecrawl.dev`.

    **Under that arm `anydoc` is an external service, so it is replaced behind the
    adapter that calls it** (`[TEST3]`) and the case asserts what crossed: the format
    named and the arm taken, read off the call the shipping `converted` actually made.
    Nothing of this tier is replaced — `converted` is the interface a caller uses and it
    is the real one.

    A behavioural case cannot be had here, which is why this one records the call.
    Probed on 20 September 2026 against `firecrawl-anydoc` 0.2.4: a `.docx` holding
    nothing but a bitmap — the nearest thing to a document wanting OCR — converts to the
    empty string under `"reject"` and under `"hosted"` alike, so no document tells the
    two arms apart. The only thing that would is a route to the network, which is the
    very thing being forbidden.

    The two literals above the call keep the constant honest and record that the library
    offers a second arm at all: a case reading only the library's own default would go
    on passing the day a patch release moved it.
    """
    import anydoc

    assert OCR_ANSWER == "reject"
    assert set(get_args(anydoc.Ocr)) == {"reject", "hosted"}
    assert signature(anydoc.to_markdown_bytes).parameters["ocr"].default == OCR_ANSWER

    asked: list[tuple[object, object, dict[str, object]]] = []

    # The library names its second parameter `format`; the adapter passes it
    # positionally, so the recorder is free to call it something that is not a builtin.
    def record(data: bytes, as_format: object = None, **rest: object) -> str:
        asked.append((as_format, rest.pop("ocr", None), rest))
        return "# Recorded"

    monkeypatch.setattr(anydoc, "to_markdown_bytes", record)

    assert converted(b"a zip nothing reads", DOCX_MEDIA_TYPE) == "# Recorded"
    assert asked == [("docx", "reject", {})]


# -- the converters in the memo's version ----------------------------------------------


def test_a_changed_converter_version_changes_the_memoised_functions_version() -> None:
    """A converter's output is the span address space, so an upgrade has to miss the
    memo for every document of its media type — that way a reprocess is something
    somebody chose rather than a drift nobody saw.

    Held on the pin's own function, which is a plain function of the two versions, so
    the fact under test is about the string and not about whichever versions happen to
    be installed while this runs.
    """
    assert converter_pin_of("0.2.4", "1.22.0") == "anydoc-0.2.4+pdf-inspector-1.22.0"
    assert converter_pin_of("0.2.5", "1.22.0") != converter_pin_of("0.2.4", "1.22.0")
    assert converter_pin_of("0.2.4", "1.23.0") != converter_pin_of("0.2.4", "1.22.0")
    assert f"{RULE_VERSION}:{DETECTOR_PIN}+{CONVERTER_PIN}" == MEMO_VERSION


def test_the_document_row_keeps_the_seams_version_and_not_the_converters(
    host: Host,
) -> None:
    """The other half of that pair (`[TEST7]`): the converters are in the **key** and
    never on the row. What a locator's offsets are read against is the seam's version
    string, which is what the catalogue column and every finding row carry — and a
    column that also named a converter would be a second thing to keep in step for no
    question anybody asks of it.
    """
    bucket = a_bucket_holding_both()

    answer = read_the_copies(host, bucket, (THE_INVOICE,))

    assert answer.documents[0].redacted.version == f"{RULE_VERSION}:{DETECTOR_PIN}"
    assert CONVERTER_PIN not in answer.documents[0].redacted.version


# -- the per-document timeout ----------------------------------------------------------


def test_the_timeout_is_the_seams_ms_per_page_times_the_pages_and_a_margin() -> None:
    """The derivation, written down rather than recomputed (`[TEST9]`). S0 measured the
    seam at 2841 ms a page on the worker image — the slowest of its three readings,
    because this is a ceiling — and the margin is what a document is given whatever its
    length: the one-off model load a process's first document pays, the conversion in
    front of the seam, and the engine's work around both.
    """
    assert SEAM_MS_PER_PAGE == 2841
    assert TIMEOUT_MARGIN_MS == 30_000
    assert timeout_for(1).total_seconds() == pytest.approx(32.841)
    assert timeout_for(12).total_seconds() == pytest.approx(64.092)
    assert timeout_for(12) - timeout_for(11) == timeout_for(1) - timeout_for(0)


def test_a_pdfs_pages_are_read_and_the_other_types_measured_against_s0s_page() -> None:
    """A PDF is the one type that carries a page count, and it is read out of the
    header before the conversion the ceiling is for — taking it from a conversion would
    mean knowing how long to allow only once the conversion had already returned.

    The other three have no pages, so the estimate is the landed copy's byte length over
    the 2,488-byte page S0 timed itself against. It **over-counts** a `.docx`, whose
    bytes are a zip holding images and styles as well as text, and so errs long — which
    is the right direction for a ceiling.
    """
    assert pages_of(fixture_bytes("rate-card.pdf"), PDF_MEDIA_TYPE) == 1
    assert pages_of(b"", "text/markdown") == 1
    assert pages_of(b"a" * 2488, "text/markdown") == 1
    assert pages_of(b"a" * 2489, "text/markdown") == 2
    # The `.docx` fixture is two paragraphs, a list and a table — a page of text in a
    # zip of thirty-six kilobytes, which this counts as fifteen.
    assert pages_of(fixture_bytes("expenses-policy.docx"), DOCX_MEDIA_TYPE) == 15


def test_a_document_that_runs_past_its_ceiling_is_quarantined_and_the_run_finishes(
    host: Host,
) -> None:
    """The ceiling is cooperative and per document, so a conversion that sticks is that
    document's quarantine and never the binding's: the run finishes, writes nothing
    under the document's normalised key, and names the deadline as what refused it.

    *Slow* is made by the ceiling rather than by the document, and deliberately. The
    shipped allowance is thirty-three seconds for a single page against a conversion
    that costs single-digit milliseconds, so a document slow enough to breach it on one
    machine would be a document that breached nothing on the next — and a case that
    waited for one would be a case about this laptop. A ceiling of nothing is the same
    fact stated in a way every machine agrees on.
    """
    bucket = a_bucket_holding_both()

    answer = read_the_copies(host, bucket, (THE_INVOICE,), ms_per_page=0, margin_ms=0)

    assert quarantine_of(answer) == {AN_INVOICE_ID: "DeadlineExceededError"}
    assert answer.documents == ()
    assert bucket.writes == []


def test_the_same_document_under_the_shipped_ceiling_lands(host: Host) -> None:
    """The control the case above needs (`[TEST7]`): the same document, the same run,
    the ceiling this tier ships — and it lands. Without this, a quarantine that had
    nothing to do with the deadline would read as a timeout working.
    """
    bucket = a_bucket_holding_both()

    answer = read_the_copies(host, bucket, (THE_INVOICE,))

    assert answer.quarantined == ()
    assert text_of(answer, AN_INVOICE_ID) == AN_INVOICE_REDACTED


# -- the chunks, where the run cuts them ----------------------------------------------
#
# The splitter's own arithmetic — the boundaries, the offsets, the derived id and the
# wire locator — is held against the `document-chunk` agreement in
# `tests/test_document_chunk_contract.py`, which is where both tiers' halves of that
# agreement live. What is held here is the one thing that file cannot see: that the text
# the run hands the splitter is the text the seam left behind and never the one it read.


def test_a_documents_chunks_are_cut_out_of_the_redacted_text_and_never_the_original(
    host: Host,
) -> None:
    """The order the whole design rests on (ADR 0020): the seam runs before the
    splitter, so an offset a citation carries is an offset into text a reader may see.
    """
    bucket = a_bucket_holding_both()

    answer = read_the_copies(host, bucket, (THE_INVOICE,))
    chunks: tuple[Chunk, ...] = answer.documents[0].chunks

    assert "".join(chunk.content for chunk in chunks) == AN_INVOICE_REDACTED
    assert all(THE_ACCOUNT_NUMBER not in chunk.content for chunk in chunks)
    assert chunks[0].id == f"{AN_INVOICE_ID}#000000"
    assert chunks[0].locator.startswith(f"{AN_INVOICE_ID}/chars:0-")


def test_a_suppression_is_held_as_sorted_pairs_so_one_set_has_one_key() -> None:
    """A memo key is what this value is for, so two requests naming the same identifiers
    must fingerprint alike however the rows came back. A mapping's order is the reader's
    and not the set's, which is why this is pairs and why they are sorted.
    """
    one = suppression_of({"name": ("Priya Raman",), "email": ("p@example.test",)})
    other = suppression_of({"email": ("p@example.test",), "name": ("Priya Raman",)})

    assert one == other
    assert one.identifiers == (
        ("email", ("p@example.test",)),
        ("name", ("Priya Raman",)),
    )
