import {
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { workspace } from "./workspace-table.ts";

/**
 * The identity set (ADR 0009, 2026-09-01 amendment; ADR 0032): every table Better Auth
 * 1.7.2 owns, plus `workspace` — its organisation model — which stays in `schema.ts`.
 * None of these is a tenant table: Better Auth reads them by secret or principal id
 * before any workspace is known and returns the workspace id, so they carry no
 * `workspace_id` and no RLS policy — *isolated by key, not by scope*. The RLS coverage
 * test takes `IDENTITY_SET` as its exemption list and checks the pair both ways
 * (`packages/schema/test/rls.test.ts`, "the identity set", `[TEST7]`).
 *
 * Shapes were generated by `auth@1.7.2 generate` (the Better Auth CLI, read 01/09/2026,
 * `[DEPS1]`) against this repo's plugin list and then hand-carried here with three
 * deliberate changes: every timestamp is `timestamptz`; the organisation plugin's
 * `organizationId` fields are mapped to `workspaceId` (the glossary's word, ADR 0009);
 * `member.role` has no `"member"` default because the platform's roles are Admin,
 * Editor and Viewer and Better Auth always writes one explicitly.
 */

const stamp = (name: string) => timestamp(name, { withTimezone: true, mode: "date" });

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: stamp("created_at").defaultNow().notNull(),
  updatedAt: stamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  // ADR 0018: a credential minted before this instant is refused on every call. Set by
  // the platform (Better Auth's `input: false`), never by the person.
  credentialsRevokedAt: stamp("credentials_revoked_at"),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: stamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: stamp("created_at").defaultNow().notNull(),
    updatedAt: stamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // The organisation plugin's `activeOrganizationId`, mapped to the glossary's word.
    activeWorkspaceId: text("active_workspace_id"),
  },
  (table) => [index("session_user_id_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    issuer: text("issuer").notNull(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: stamp("access_token_expires_at"),
    refreshTokenExpiresAt: stamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: stamp("created_at").defaultNow().notNull(),
    updatedAt: stamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    uniqueIndex("account_issuer_account_id_uidx").on(table.issuer, table.accountId),
    index("account_user_id_idx").on(table.userId),
  ],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: stamp("expires_at").notNull(),
    createdAt: stamp("created_at").defaultNow().notNull(),
    updatedAt: stamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const jwks = pgTable("jwks", {
  id: text("id").primaryKey(),
  publicKey: text("public_key").notNull(),
  privateKey: text("private_key").notNull(),
  createdAt: stamp("created_at").notNull(),
  expiresAt: stamp("expires_at"),
  alg: text("alg"),
  crv: text("crv"),
});

export const member = pgTable(
  "member",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspace.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // Admin, Editor or Viewer (CONTEXT.md, *role (of a person)*); the boundary narrows it.
    role: text("role").notNull(),
    createdAt: stamp("created_at").notNull(),
  },
  (table) => [
    index("member_workspace_id_idx").on(table.workspaceId),
    index("member_user_id_idx").on(table.userId),
    // The resolver's one indexed read (ADR 0018): a person is a member of a workspace once.
    uniqueIndex("member_workspace_id_user_id_uidx").on(table.workspaceId, table.userId),
  ],
);

export const invitation = pgTable(
  "invitation",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspace.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    role: text("role"),
    status: text("status").default("pending").notNull(),
    expiresAt: stamp("expires_at").notNull(),
    createdAt: stamp("created_at").defaultNow().notNull(),
    inviterId: text("inviter_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [
    index("invitation_workspace_id_idx").on(table.workspaceId),
    index("invitation_email_idx").on(table.email),
  ],
);

export const oauthClient = pgTable(
  "oauth_client",
  {
    id: text("id").primaryKey(),
    clientId: text("client_id").notNull().unique(),
    clientSecret: text("client_secret"),
    // "cimd" on a client discovered from its metadata document — the row CONTEXT.md's
    // *client (connected)* entry describes. There is no registration.
    clientDiscoveryId: text("client_discovery_id"),
    disabled: boolean("disabled").default(false),
    skipConsent: boolean("skip_consent"),
    enableEndSession: boolean("enable_end_session"),
    subjectType: text("subject_type"),
    scopes: text("scopes").array(),
    clientCredentialsScopes: text("client_credentials_scopes").array().default([]),
    userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
    createdAt: stamp("created_at"),
    updatedAt: stamp("updated_at"),
    name: text("name"),
    uri: text("uri"),
    icon: text("icon"),
    contacts: text("contacts").array(),
    tos: text("tos"),
    policy: text("policy"),
    softwareId: text("software_id"),
    softwareVersion: text("software_version"),
    softwareStatement: text("software_statement"),
    redirectUris: text("redirect_uris").array().notNull(),
    postLogoutRedirectUris: text("post_logout_redirect_uris").array(),
    backchannelLogoutUri: text("backchannel_logout_uri"),
    backchannelLogoutSessionRequired: boolean("backchannel_logout_session_required"),
    tokenEndpointAuthMethod: text("token_endpoint_auth_method"),
    applicationType: text("application_type"),
    jwks: text("jwks"),
    jwksUri: text("jwks_uri"),
    grantTypes: text("grant_types").array(),
    responseTypes: text("response_types").array(),
    requirePKCE: boolean("require_pkce"),
    dpopBoundAccessTokens: boolean("dpop_bound_access_tokens").default(false),
    referenceId: text("reference_id"),
    metadata: jsonb("metadata"),
  },
  (table) => [index("oauth_client_user_id_idx").on(table.userId)],
);

export const oauthResource = pgTable("oauth_resource", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull().unique(),
  name: text("name").notNull(),
  accessTokenTtl: integer("access_token_ttl"),
  refreshTokenTtl: integer("refresh_token_ttl"),
  signingAlgorithm: text("signing_algorithm"),
  signingKeyId: text("signing_key_id"),
  allowedScopes: text("allowed_scopes").array(),
  customClaims: jsonb("custom_claims"),
  dpopBoundAccessTokensRequired: boolean("dpop_bound_access_tokens_required").default(false),
  disabled: boolean("disabled").default(false),
  createdAt: stamp("created_at"),
  updatedAt: stamp("updated_at"),
  policyVersion: integer("policy_version").default(1),
  metadata: jsonb("metadata"),
});

export const oauthClientResource = pgTable(
  "oauth_client_resource",
  {
    id: text("id").primaryKey(),
    clientId: text("client_id")
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: "cascade" }),
    resourceId: text("resource_id")
      .notNull()
      .references(() => oauthResource.identifier, { onDelete: "cascade" }),
    metadata: jsonb("metadata"),
    createdAt: stamp("created_at"),
  },
  (table) => [
    uniqueIndex("oauth_client_resource_client_id_resource_id_uidx").on(
      table.clientId,
      table.resourceId,
    ),
    index("oauth_client_resource_client_id_idx").on(table.clientId),
    index("oauth_client_resource_resource_id_idx").on(table.resourceId),
  ],
);

export const oauthRefreshToken = pgTable(
  "oauth_refresh_token",
  {
    id: text("id").primaryKey(),
    token: text("token").notNull().unique(),
    clientId: text("client_id")
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: "cascade" }),
    sessionId: text("session_id").references(() => session.id, { onDelete: "set null" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // Better Auth's own carrier of the workspace id on a grant (research, 2026-09-01).
    referenceId: text("reference_id"),
    authorizationCodeId: text("authorization_code_id"),
    resources: text("resources").array(),
    requestedUserInfoClaims: text("requested_user_info_claims").array(),
    expiresAt: stamp("expires_at").notNull(),
    createdAt: stamp("created_at").notNull(),
    revoked: stamp("revoked"),
    rotatedAt: stamp("rotated_at"),
    rotationReplayResponse: text("rotation_replay_response"),
    rotationReplayExpiresAt: stamp("rotation_replay_expires_at"),
    authTime: stamp("auth_time"),
    confirmation: jsonb("confirmation"),
    scopes: text("scopes").array().notNull(),
  },
  (table) => [
    index("oauth_refresh_token_client_id_idx").on(table.clientId),
    index("oauth_refresh_token_session_id_idx").on(table.sessionId),
    index("oauth_refresh_token_user_id_idx").on(table.userId),
    index("oauth_refresh_token_authorization_code_id_idx").on(table.authorizationCodeId),
  ],
);

export const oauthAccessToken = pgTable(
  "oauth_access_token",
  {
    id: text("id").primaryKey(),
    token: text("token").notNull().unique(),
    clientId: text("client_id")
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: "cascade" }),
    sessionId: text("session_id").references(() => session.id, { onDelete: "set null" }),
    userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
    referenceId: text("reference_id"),
    authorizationCodeId: text("authorization_code_id"),
    resources: text("resources").array(),
    requestedUserInfoClaims: text("requested_user_info_claims").array(),
    refreshId: text("refresh_id").references(() => oauthRefreshToken.id, {
      onDelete: "cascade",
    }),
    expiresAt: stamp("expires_at").notNull(),
    createdAt: stamp("created_at").notNull(),
    revoked: stamp("revoked"),
    confirmation: jsonb("confirmation"),
    scopes: text("scopes").array().notNull(),
  },
  (table) => [
    index("oauth_access_token_client_id_idx").on(table.clientId),
    index("oauth_access_token_session_id_idx").on(table.sessionId),
    index("oauth_access_token_user_id_idx").on(table.userId),
    index("oauth_access_token_authorization_code_id_idx").on(table.authorizationCodeId),
    index("oauth_access_token_refresh_id_idx").on(table.refreshId),
  ],
);

export const oauthConsent = pgTable(
  "oauth_consent",
  {
    id: text("id").primaryKey(),
    clientId: text("client_id")
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: "cascade" }),
    userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
    referenceId: text("reference_id"),
    resources: text("resources").array(),
    requestedUserInfoClaims: text("requested_user_info_claims").array(),
    scopes: text("scopes").array().notNull(),
    createdAt: stamp("created_at").notNull(),
    updatedAt: stamp("updated_at").notNull(),
  },
  (table) => [
    index("oauth_consent_client_id_idx").on(table.clientId),
    index("oauth_consent_user_id_idx").on(table.userId),
  ],
);

export const oauthClientAssertion = pgTable("oauth_client_assertion", {
  id: text("id").primaryKey(),
  expiresAt: stamp("expires_at").notNull(),
});

/** Better Auth's own limiter, database-backed (`rateLimit.storage: "database"`). */
export const rateLimit = pgTable("rate_limit", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  lastRequest: bigint("last_request", { mode: "number" }).notNull(),
});

/**
 * The identity set by name — the RLS coverage test's exemption list. Sixteen tables:
 * Better Auth's core four, the JWT plugin's one, the organisation plugin's three
 * (`workspace` is its organisation model), the OAuth provider's seven and the limiter's.
 */
export const IDENTITY_SET = [
  "public.user",
  "public.session",
  "public.account",
  "public.verification",
  "public.jwks",
  "public.workspace",
  "public.member",
  "public.invitation",
  "public.oauth_client",
  "public.oauth_resource",
  "public.oauth_client_resource",
  "public.oauth_refresh_token",
  "public.oauth_access_token",
  "public.oauth_consent",
  "public.oauth_client_assertion",
  "public.rate_limit",
] as const;
