// Generated, never edited: pnpm --filter @better-answers/core run generate:audit-actions

export const DECLARED_ACTIONS = [
  "knowledge.check.imported",
  "knowledge.concept.class_overridden",
  "knowledge.concept.committed",
  "knowledge.manifest.written",
  "knowledge.suggestion.accepted",
  "knowledge.suggestion.declined",
  "knowledge.suggestion.returned",
  "people.client.consented",
  "people.erasure.completed",
  "people.group.created",
  "people.group.deleted",
  "people.group.member_added",
  "people.group.member_removed",
  "people.group.renamed",
  "people.invitation.cancelled",
  "people.invitation.created",
  "people.invitation.resent",
  "people.member.added",
  "people.member.credentials_revoked",
  "people.member.joined",
  "people.member.removed",
  "people.member.role_changed",
  "people.name_flag.raised",
  "people.operator.granted",
  "people.operator.revoked",
  "people.person.added",
  "people.person.authenticator_added",
  "people.person.authenticator_removed",
  "people.person.credentials_revoked",
  "people.person.factors_replaced",
  "people.person.grants_ended",
  "people.person.name_flagged",
  "people.person.named",
  "people.person.passkey_added",
  "people.person.passkey_removed",
  "people.person.passkey_renamed",
  "people.person.recovery_code_used",
  "people.person.recovery_codes_issued",
  "people.person.renamed",
  "people.person.restore_code_accepted",
  "people.person.second_factor_confirmed",
  "people.person.sign_in_restored",
  "people.person.signed_in",
  "people.request.approved",
  "people.request.asked",
  "people.request.declined",
  "people.subject_request.received",
  "platform.audit_log.exported",
  "platform.erasure.rehearsed",
  "platform.erasure.replayed",
  "platform.graph.swept",
  "platform.job.followed",
  "platform.reconciler.replayed",
  "platform.workspace.marked",
  "platform.workspace.provisioned",
  "platform.workspace.renamed",
  "sources.binding.bound",
  "sources.binding.narrowed",
  "sources.binding.published",
  "sources.binding.widened",
  "sources.document.narrowed",
  "sources.document.special_category_dismissed",
  "sources.finding.restored",
  "sources.upload.swept",
] as const;

export const HEADLINES = {
  "knowledge.check.imported": "Verification imported",
  "knowledge.concept.class_overridden": "Sensitivity overridden",
  "knowledge.concept.committed": "Concept saved",
  "knowledge.manifest.written": "Knowledge base description updated",
  "knowledge.suggestion.accepted": "Suggestion accepted",
  "knowledge.suggestion.declined": "Suggestion declined",
  "knowledge.suggestion.returned": "Suggestion sent back",
  "people.client.consented": "Assistant given access",
  "people.erasure.completed": "Erasure request carried out",
  "people.group.created": "Group created",
  "people.group.deleted": "Group deleted",
  "people.group.member_added": "Added to a group",
  "people.group.member_removed": "Removed from a group",
  "people.group.renamed": "Group renamed",
  "people.invitation.cancelled": "Invitation cancelled",
  "people.invitation.created": "Invitation sent",
  "people.invitation.resent": "Invitation resent",
  "people.member.added": "Member added",
  "people.member.credentials_revoked": "Every sign-in and token ended here",
  "people.member.joined": "Member joined",
  "people.member.removed": "Member removed",
  "people.member.role_changed": "Role changed",
  "people.name_flag.raised": "Display name flagged to support",
  "people.operator.granted": "Made better-answers support",
  "people.operator.revoked": "Taken off better-answers support",
  "people.person.added": "Person added",
  "people.person.authenticator_added": "Authenticator set up",
  "people.person.authenticator_removed": "Authenticator removed",
  "people.person.credentials_revoked": "Every sign-in and token ended everywhere",
  "people.person.factors_replaced": "Second factors replaced",
  "people.person.grants_ended": "Assistant access ended",
  "people.person.name_flagged": "Display name flagged",
  "people.person.named": "Display name given",
  "people.person.passkey_added": "Passkey added",
  "people.person.passkey_removed": "Passkey removed",
  "people.person.passkey_renamed": "Passkey renamed",
  "people.person.recovery_code_used": "Recovery code used",
  "people.person.recovery_codes_issued": "Recovery codes given",
  "people.person.renamed": "Display name corrected",
  "people.person.restore_code_accepted": "Restore code used",
  "people.person.second_factor_confirmed": "Second factor confirmed",
  "people.person.sign_in_restored": "Sign-in restored",
  "people.person.signed_in": "Signed in",
  "people.request.approved": "Access request approved",
  "people.request.asked": "Access requested",
  "people.request.declined": "Access request declined",
  "people.subject_request.received": "Subject request recorded",
  "platform.audit_log.exported": "Audit log exported",
  "platform.erasure.rehearsed": "Erasure tested",
  "platform.erasure.replayed": "Erasure re-applied",
  "platform.graph.swept": "Older map copies cleared",
  "platform.job.followed": "Visibility updated after a sync",
  "platform.reconciler.replayed": "Change re-applied",
  "platform.workspace.marked": "Invitations kept to the testing domain",
  "platform.workspace.provisioned": "Workspace provisioned",
  "platform.workspace.renamed": "Workspace renamed",
  "sources.binding.bound": "Connected source added",
  "sources.binding.narrowed": "Connected source narrowed",
  "sources.binding.published": "Connected source published",
  "sources.binding.widened": "Connected source widened",
  "sources.document.narrowed": "Document narrowed",
  "sources.document.special_category_dismissed": "Findings dismissed",
  "sources.finding.restored": "Finding kept in text",
  "sources.upload.swept": "Unused upload deleted",
} as const satisfies Readonly<Record<(typeof DECLARED_ACTIONS)[number], string>>;

export const DETAIL_KEYS = [
  ["knowledge.check.imported", "iri"],
  ["knowledge.check.imported", "verificationId"],
  ["knowledge.concept.class_overridden", "audience"],
  ["knowledge.concept.class_overridden", "iri"],
  ["knowledge.concept.class_overridden", "sensitivity"],
  ["knowledge.concept.committed", "commitSha"],
  ["knowledge.concept.committed", "contentHash"],
  ["knowledge.concept.committed", "evidenceCount"],
  ["knowledge.concept.committed", "iri"],
  ["knowledge.manifest.written", "bundleId"],
  ["knowledge.manifest.written", "commitSha"],
  ["knowledge.suggestion.accepted", "commitSha"],
  ["knowledge.suggestion.accepted", "contentHash"],
  ["knowledge.suggestion.accepted", "iri"],
  ["knowledge.suggestion.accepted", "setId"],
  ["knowledge.suggestion.declined", "setId"],
  ["knowledge.suggestion.returned", "setId"],
  ["people.erasure.completed", "locations"],
  ["people.erasure.completed", "personId"],
  ["people.erasure.completed", "subjectRequestId"],
  ["people.group.member_added", "userId"],
  ["people.group.member_removed", "userId"],
  ["people.invitation.cancelled", "replacedByInvitationId"],
  ["people.invitation.created", "role"],
  ["people.member.added", "role"],
  ["people.member.added", "userId"],
  ["people.member.credentials_revoked", "grants"],
  ["people.member.joined", "invitationId"],
  ["people.member.joined", "role"],
  ["people.member.removed", "grants"],
  ["people.member.removed", "role"],
  ["people.member.role_changed", "previousRole"],
  ["people.member.role_changed", "role"],
  ["people.name_flag.raised", "workspaceId"],
  ["people.person.authenticator_added", "authenticatorId"],
  ["people.person.authenticator_removed", "authenticatorId"],
  ["people.person.credentials_revoked", "grants"],
  ["people.person.factors_replaced", "by"],
  ["people.person.grants_ended", "grants"],
  ["people.person.grants_ended", "workspaceId"],
  ["people.person.passkey_added", "passkeyId"],
  ["people.person.passkey_removed", "passkeyId"],
  ["people.person.passkey_renamed", "passkeyId"],
  ["people.person.recovery_codes_issued", "replaced"],
  ["people.person.second_factor_confirmed", "method"],
  ["people.person.signed_in", "method"],
  ["people.request.approved", "invitationId"],
  ["people.request.approved", "requesterId"],
  ["people.request.approved", "role"],
  ["people.request.asked", "requesterId"],
  ["people.request.declined", "requesterId"],
  ["people.subject_request.received", "identifierCount"],
  ["people.subject_request.received", "personId"],
  ["platform.audit_log.exported", "capped"],
  ["platform.audit_log.exported", "eventCount"],
  ["platform.audit_log.exported", "family"],
  ["platform.audit_log.exported", "matched"],
  ["platform.audit_log.exported", "searchTooBroad"],
  ["platform.erasure.rehearsed", "erasureRequestId"],
  ["platform.erasure.rehearsed", "personId"],
  ["platform.erasure.rehearsed", "subjectRequestId"],
  ["platform.erasure.rehearsed", "tokens"],
  ["platform.erasure.replayed", "erasureRequestId"],
  ["platform.erasure.replayed", "fromReplayCopy"],
  ["platform.erasure.replayed", "subjectRequestId"],
  ["platform.graph.swept", "edges"],
  ["platform.graph.swept", "generation"],
  ["platform.graph.swept", "nodes"],
  ["platform.job.followed", "attempts"],
  ["platform.job.followed", "bindingId"],
  ["platform.job.followed", "concepts"],
  ["platform.job.followed", "documents"],
  ["platform.job.followed", "writeUps"],
  ["platform.reconciler.replayed", "bundleId"],
  ["platform.reconciler.replayed", "commitSha"],
  ["platform.reconciler.replayed", "contentHash"],
  ["platform.reconciler.replayed", "evidenceAgrees"],
  ["platform.reconciler.replayed", "iri"],
  ["platform.workspace.marked", "corrected"],
  ["platform.workspace.provisioned", "adminUserId"],
  ["platform.workspace.provisioned", "role"],
  ["platform.workspace.renamed", "nameChanged"],
  ["platform.workspace.renamed", "slugChanged"],
  ["sources.binding.bound", "audience"],
  ["sources.binding.bound", "bindingId"],
  ["sources.binding.bound", "documentId"],
  ["sources.binding.bound", "sensitivity"],
  ["sources.binding.narrowed", "audience"],
  ["sources.binding.narrowed", "bindingId"],
  ["sources.binding.narrowed", "sensitivity"],
  ["sources.binding.published", "audience"],
  ["sources.binding.published", "bindingId"],
  ["sources.binding.published", "dpiaHash"],
  ["sources.binding.published", "dpiaReferenced"],
  ["sources.binding.published", "findingsBankDetails"],
  ["sources.binding.published", "findingsDateOfBirth"],
  ["sources.binding.published", "findingsGovernmentIdentifier"],
  ["sources.binding.published", "findingsHomeAddress"],
  ["sources.binding.published", "findingsJobTitle"],
  ["sources.binding.published", "findingsPersonName"],
  ["sources.binding.published", "findingsPersonalContact"],
  ["sources.binding.published", "findingsSpecialCategory"],
  ["sources.binding.published", "lawfulBasisRecorded"],
  ["sources.binding.published", "privacyInformationUpdated"],
  ["sources.binding.published", "sensitivity"],
  ["sources.binding.widened", "audience"],
  ["sources.binding.widened", "bindingId"],
  ["sources.binding.widened", "fromAudience"],
  ["sources.binding.widened", "fromSensitivity"],
  ["sources.binding.widened", "sensitivity"],
  ["sources.document.narrowed", "bindingId"],
  ["sources.document.narrowed", "documentId"],
  ["sources.document.narrowed", "sensitivity"],
  ["sources.document.special_category_dismissed", "bindingId"],
  ["sources.document.special_category_dismissed", "documentId"],
  ["sources.document.special_category_dismissed", "findingCount"],
  ["sources.finding.restored", "findingId"],
  ["sources.upload.swept", "bindingId"],
  ["sources.upload.swept", "documentId"],
] as const satisfies readonly (readonly [(typeof DECLARED_ACTIONS)[number], string])[];
