#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-deploy/wizard-41.env}"   # facts only, never a secret; gitignored
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — ticket 41: the eight steps only Liam can take (briefing §5, deploy/SECRETS.md).
# Secrets are NEVER written by this wizard: it tells you where each one goes (Coolify env,
# the escrow vault) and captures only facts — URLs, names, UUIDs — into deploy/wizard-41.env,
# plus the three GitHub variables and the one GitHub secret the workflows read.

TOTAL_STAGES=9
banner "Better Answers — ticket 41: accounts, boxes, edge, control plane (stages 1, 4, 7, 8 and one drill before the first client's data; the rest may follow go-live)"

# ────────────────────────────────────────────────────────────────────────
stage "Escrow vault"
say "Four secrets must exist outside Coolify or a VPC 2 loss takes everything with it:"
say "Coolify APP_KEY · KEK · the backup bucket's ADMIN credential · the tunnel token."
step "In your password manager create a vault for this deployment's escrow."
step "Share it with one other named person before the first client goes live (SECRETS.md)."
ask ESCROW_VAULT "Name of the vault as created:"
say "Six items will land here: APP_KEY · Coolify SSH keys · KEK · the backup age identity · the bucket ADMIN credential · the tunnel token (plus the ghcr pull token, the git-mirror deploy key and every account's recovery codes)."
step "Name the SECOND holder (co-director, solicitor) and write the instruction under which they open it. One holder is the outage the backups exist for."
ask ESCROW_SECOND_HOLDER "Second holder (name or role):"
write_env ESCROW_VAULT "$ESCROW_VAULT"; write_env ESCROW_SECOND_HOLDER "$ESCROW_SECOND_HOLDER"

# ────────────────────────────────────────────────────────────────────────
stage "GitHub — organisation, repository, protection, Renovate"
open_url "https://github.com/organizations/plan"
step "Create the organisation 'betteranswers' (ticket 63) — or the name you settled on."
ask GH_ORG "Organisation name:"
open_url "https://github.com/organizations/$GH_ORG/repositories/new"
step "Create a PRIVATE repository 'better-answers' (62 decides public; the flip is free)."
ask GH_REPO "Repository name:"
say "Push this repository:"
note "  git remote add origin git@github.com:$GH_ORG/$GH_REPO.git && git push -u origin main"
pause "Pushed?"
open_url "https://github.com/$GH_ORG/$GH_REPO/settings/branches"
step "Add a ruleset for 'main': require a pull request, require the 'check' status check."
open_url "https://github.com/$GH_ORG/$GH_REPO/settings/environments"
step "Create environments 'staging' (no reviewers) and 'production' (required reviewer: you)."
open_url "https://github.com/apps/renovate"
step "Install the Renovate app on the organisation, scoped to this repository (renovate.json is at the root)."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Fine-grained PAT 'coolify-ghcr-pull': resource owner $GH_ORG, permission Packages: read only, one year. It becomes Coolify's registry credential on VPC 1 and VPC 2 (stage 7) and is escrowed."
warn "Do not paste it here."
write_env GH_ORG "$GH_ORG"; write_env GH_REPO "$GH_REPO"
pause

# ────────────────────────────────────────────────────────────────────────
stage "IONOS — the two VPS (4 vCPU · 4 GB · 120 GB NVMe each)"
open_url "https://cloud.ionos.co.uk/"
say "The two existing contracts, 4 vCPU / 4 GB / 120 GB NVMe each; they cannot be resized (ADR 0024). No private network joins them."
step "VPC 1 — production: Ubuntu LTS; your SSH key. Create the 4 GB swap file (deploy/RUNBOOK.md § Swap) before the first deploy."
step "VPC 2 — Coolify + git mirror + restore target (staging on demand)."
step "Firewall: inbound SSH only — from your IP to both, from VPC 2 to VPC 1, AND from VPC 1 to VPC 2 (the git push mirror travels to VPC 2's public IP). Nothing else inbound."
step "On both: unattended security upgrades on, fail2ban, password SSH off, NTP running (object-lock dates and token iat checks trust the clock)."
ask VPC1_PUBLIC_IP  "VPC 1 public IP (SSH from VPC 2 and you only):"
ask VPC2_PUBLIC_IP  "VPC 2 public IP:"
step "On VPC 1: sudo mkdir -p /data && sudo chmod 755 /data  (bind mounts live here — compose.yaml). Generate the git-mirror deploy keypair: ssh-keygen -t ed25519 -f /data/backup/mirror-ssh/id_ed25519 -N ''  (root-only directory; the backup service mounts it read-only); escrow the private half."
step "On VPC 2: create a 'mirror' user with sudo mkdir -p /data/mirror owned by it; add the deploy key's PUBLIC half to its authorized_keys restricted to git-receive-pack; git clone the repository to /opt/better-answers (the drill runs from there by host cron). GIT_MIRROR_SSH_TARGET in Coolify env = mirror@$VPC2_PUBLIC_IP:/data/mirror."
step "The drill restores the whole estate beside Coolify on VPC 2 with production's caps — there is no bigger plan; the swap-in probe (deploy/coolify.md) decides the WireGuard split."
write_env VPC1_PUBLIC_IP "$VPC1_PUBLIC_IP"
write_env VPC2_PUBLIC_IP "$VPC2_PUBLIC_IP"
pause

# ────────────────────────────────────────────────────────────────────────
stage "Backup bucket — versioning + object lock, two credentials"
say "Provider: the one research 70 ranked first (.scratch/v01-spec/research/41-object-store-and-bucket.md) — UK preferred, EU fine; object lock; a UK-addendum DPA."
ask BACKUP_S3_PROVIDER "Provider chosen:"
ask BACKUP_S3_ENDPOINT "S3 endpoint URL:"
ask BACKUP_DUMPS_BUCKET "DUMPS bucket name (versioning ON, object lock ON in GOVERNANCE mode):"
step "Lifecycle on the dumps bucket: pg/hourly 48 h · pg/daily 30 d · pg/weekly 8 w · pg/monthly 6 m · git/ 30 d (+ first-of-month 6 m) · drills/ 12 m (BACKUPS.md)."
ask BACKUP_MIRROR_BUCKET "MIRROR bucket name (versioning ON, NO lock, non-current versions expire after 30 days):"
step "Credential 1 — WRITE-AND-LIST (PutObject, ListBucket, GetObject; no Delete*, no lifecycle, no bypass-governance) → Coolify env BACKUP_S3_ACCESS_KEY / _SECRET_KEY and Coolify's S3 storage."
step "Credential 2 — READ (list + get on both buckets) → VPC 2 host env for the drill, root-only file."
step "Credential 3 — ADMIN (delete, lifecycle, bypass governance). Escrow only."
step "Generate the backup age keypair on your laptop: age-keygen -o backup.key  → the public 'age1…' line goes to Coolify env as BACKUP_AGE_RECIPIENT; the file goes to escrow and is deleted from the laptop."
warn "Do not paste any credential or key here."
write_env BACKUP_S3_PROVIDER "$BACKUP_S3_PROVIDER"; write_env BACKUP_S3_ENDPOINT "$BACKUP_S3_ENDPOINT"; write_env BACKUP_DUMPS_BUCKET "$BACKUP_DUMPS_BUCKET"; write_env BACKUP_MIRROR_BUCKET "$BACKUP_MIRROR_BUCKET"
pause

# ────────────────────────────────────────────────────────────────────────
stage "Cloudflare — zone, tunnel, Access, rate limits, Pages"
ask APEX "Apex domain for this deployment (e.g. example.com):"
write_env APEX "$APEX"
open_url "https://dash.cloudflare.com/"
step "Add the zone $APEX (nameservers at the registrar)."
open_url "https://one.dash.cloudflare.com/"
step "Zero Trust → Networks → Tunnels → create tunnel 'better-answers' (remotely managed). Copy the TUNNEL TOKEN into Coolify env later (TUNNEL_TOKEN) and escrow it."
step "Public hostnames on the tunnel, all → http://app:3000 : app. · mcp. · agent. · the apex ($APEX); the last ingress rule is the catch-all http_status:404."
step "Access → Applications: 'app' for app.$APEX — policy Allow, emails: yours + the first client's; login method One-time PIN. The machine hostnames authenticate in the app (OAuth 2.1 on mcp., an agent token on agent.), so an interactive Access policy on them would break the client that must reach them (ADRs 0008, 0018)."
step "Security → WAF → Rate limiting: the Free plan allows ONE rule — put it on the agent hostname, the one route that streams uploads (the MCP surface is limited per token inside the app, ADR 0018). On Pro, add a second rule. Record where each rule sits in the estate file, never here. Tighten after the first week."
step "Docs site: keep the existing Vercel project (Astro); point it at this repo's docs-site/ and add the custom domain docs.$APEX (CNAME in Cloudflare DNS, DNS-only). No Cloudflare Pages project (28/08/2026)."
ask CF_TUNNEL_ID "Tunnel ID (not the token):"
write_env CF_TUNNEL_ID "$CF_TUNNEL_ID"
pause

# ────────────────────────────────────────────────────────────────────────
stage "Transactional email — sign-in codes, invitations, Coolify notifications"
say "Better Auth's email-code login, invitations and Coolify's alerts all need SMTP. A UK/EU-hosted provider preferred; any with a DPA."
step "Create the account; verify the sending domain $APEX (SPF, DKIM, DMARC records in Cloudflare DNS)."
step "Create one API key → (a) Coolify env SMTP_URL on the production stack: smtps://resend:<API key>@smtp.resend.com:465 ; (b) Coolify Settings → Notifications → Resend (the same key) for Coolify's own alerts. Two places, one key."
ask SMTP_PROVIDER "Provider chosen:"
write_env SMTP_PROVIDER "$SMTP_PROVIDER"
pause

# ────────────────────────────────────────────────────────────────────────
stage "Coolify on VPC 2 — control plane, resources, backups, notifications"
say "Install on VPC 2 at the PINNED version v4.3.13 (28/08/2026); Settings → Update: auto-update OFF. Reach the UI over SSH forwarding, or behind Access if exposed."
step "Settings → Backup: escrow APP_KEY (from /data/coolify/source/.env) AND /data/coolify/ssh/keys/ in '$ESCROW_VAULT'; enable the instance backup to S3 storage '$BACKUP_DUMPS_BUCKET/coolify/', daily."
step "Servers → add VPC 1 over SSH ($VPC1_PUBLIC_IP)."
step "Storages → S3: '$BACKUP_S3_PROVIDER' with the WRITE-AND-LIST credential."
step "Registries (or the resource's registry credential): ghcr.io with the pull PAT from stage 2 — on both servers."
step "On VPC 1: Database → PostgreSQL, image ghcr.io/betteranswers/postgres by digest (deploy/postgres.Dockerfile), name 'better-answers-pg', shared_buffers 512 MB, data directory bind-mounted at /data/postgres if the UI allows (record the answer in deploy/coolify.md); Backups → S3 storage, daily — the tiers are the backup service's, not Coolify's."
step "On VPC 1: Docker Compose 'better-answers-stores' from deploy/stores.compose.yaml, then 'better-answers' from deploy/platform.compose.yaml (git source = the GitHub repo). Paste every env in deploy/SECRETS.md that says 'Coolify env'."
step "On VPC 2: only the staging Postgres resource is created (empty); the two staging stacks are brought up ON DEMAND by the drill or by hand (deploy/RUNBOOK.md § Bring staging up) and wiped after. The drill is HOST CRON on VPC 2, not a Coolify task: sudo crontab -e → 0 3 1 * * /opt/better-answers/deploy/restore-drill.sh (env from a root-only file)."
step "Settings → Notifications → email: failed deployments, unhealthy containers, backup failures."
step "Keys & Tokens → API tokens: create 'github-actions-deploy' (deploy scope)."
say "CI (GitHub-hosted runners) cannot reach Coolify while the firewall allows only your own address. COOLIFY_URL waits until Coolify is reachable by CI — a second tunnel on VPC 2 (coolify.\$APEX → localhost:8000) behind Access with a service token for CI is the recommended shape; leave '-' until then."
ask COOLIFY_URL "Coolify URL (as CI will reach it; '-' if not yet):"
ask COOLIFY_STAGING_APP_UUID "UUID of the STAGING compose resource:"
ask COOLIFY_PROD_APP_UUID "UUID of the PRODUCTION compose resource:"
ask_secret COOLIFY_DEPLOY_TOKEN "Paste the API token (hidden; goes to GitHub only):"
set_var COOLIFY_URL "$COOLIFY_URL"
set_var COOLIFY_STAGING_APP_UUID "$COOLIFY_STAGING_APP_UUID"
set_var COOLIFY_PROD_APP_UUID "$COOLIFY_PROD_APP_UUID"
set_secret COOLIFY_DEPLOY_TOKEN "$COOLIFY_DEPLOY_TOKEN"
write_env COOLIFY_URL "$COOLIFY_URL"; write_env COOLIFY_STAGING_APP_UUID "$COOLIFY_STAGING_APP_UUID"; write_env COOLIFY_PROD_APP_UUID "$COOLIFY_PROD_APP_UUID"
pause

# ────────────────────────────────────────────────────────────────────────
stage "healthchecks.io — the dead-man's switch"
open_url "https://healthchecks.io/"
step "Create a project 'Better Answers'. Checks (period · grace): scheduler 1 min · 3 min; pg-hourly 1 h · 15 min; nightly 24 h · 2 h; coolify-backup 24 h · 4 h; drill 35 d · 2 d; staging-wiped 35 d · 2 d."
step "Ping URLs → Coolify env: HEALTHCHECKS_PING_URL_SCHEDULER, _PG_HOURLY, _NIGHTLY (production stacks); _DRILL and _STAGING_WIPED → the VPC 2 host env file. Ping bodies carry an outcome word and sizes only."
step "Integrations: email to you; add a second channel (SMS or a chat app) for 'scheduler' — silence there is an outage."
pause "Ping URLs in Coolify env?"

# ────────────────────────────────────────────────────────────────────────
stage "First deploy, the depends_on probe, the first drill"
say "In GitHub → Actions run 'build' (main): the images are pushed; staging deploys only when brought up. Then run 'release' to promote to production."
step "Watch the production deploy log in Coolify. Record in deploy/coolify.md § Probes: the compose command Coolify ran; whether 'migrate' finished before 'app' started; whether 'worker' waited for 'app' healthy; whether redeploying 'better-answers' left 'better-answers-stores' running."
step "Open https://app.$APEX (Access OTP), https://mcp.$APEX/.well-known/oauth-protected-resource, https://agent.$APEX/ (expect 404), https://$APEX/c/test (expect 404)."
step "Run the first drill by hand on VPC 2: sudo /opt/better-answers/deploy/restore-drill.sh. Read the report in the bucket under drills/. Then rehearse 'Coolify lost' once (deploy/RUNBOOK.md page 5) and test that the second holder can open the vault."
if confirm "All four hostnames answered as expected and the drill report exists"; then
  write_env FIRST_DEPLOY_DONE "$(date -u +%F)"
else
  SKIPPED+=("first deploy / probe / drill — re-run this stage")
fi

finish
