window.BAData = {
  workspace: "Northgate Facilities",
  mapAsOf: "09:41 · 30 August 2026",
  answer: {
    verdict: "Answered from the map",
    prose: [
      {
        text: "Northgate holds ISO 27001 certification for its managed facilities service, first certified in March 2023 and audited annually by BSI.",
        marker: "1",
      },
      {
        text: "The certificate covers the Manchester and Leeds operating centres; the Glasgow centre is in scope from the 2026 surveillance audit.",
        marker: "2",
      },
      { text: "All processing of client data takes place in the United Kingdom.", marker: "3" },
    ],
    unanswered: "Nothing on the map states the certificate's expiry date.",
    citations: [
      {
        marker: "1",
        concept: "ISO 27001 certification",
        source: "Capability statement",
        locator: "p.4",
        passage: "Certified to ISO 27001 since March 2023, audited annually by BSI.",
        state: "checked",
        by: "Priya Shah",
        at: "3 March 2026",
      },
      {
        marker: "2",
        concept: "Certified operating centres",
        source: "ISMS scope statement",
        locator: "§2.1",
        passage:
          "In scope: Manchester (M4 2AF), Leeds (LS1 4DY). Glasgow enters scope at the 2026 surveillance audit.",
        state: "checked-by-platform",
      },
      {
        marker: "3",
        concept: "Data processing locations",
        source: "Northgate DPA",
        locator: "§7.2",
        passage: "All processing takes place in the United Kingdom.",
        state: "out-of-date",
      },
    ],
  },
  hits: [
    {
      layer: "Concept",
      title: "ISO 27001 certification",
      kind: "Certification",
      state: "checked",
      by: "Priya Shah",
      at: "3 March 2026",
      sub: ["Product guide — Managed service · Security", "Capability statement (p.4)"],
    },
    {
      layer: "Concept",
      title: "Certified operating centres",
      kind: "Entity",
      state: "checked-by-platform",
      sub: ["ISMS scope statement (§2.1)"],
    },
    {
      layer: "Concept",
      title: "Data processing locations",
      kind: "Policy",
      state: "out-of-date",
      sub: ["Northgate DPA (§7.2)"],
    },
    {
      layer: "Document",
      title: "Surveillance audit report 2025.pdf",
      state: "restricted",
      sub: ["Not company knowledge · SharePoint · 12 February 2026"],
    },
  ],
  guide: {
    subject: "Managed facilities service",
    sections: [
      {
        name: "What it is",
        coverage: [6, 6],
        brief:
          "A managed facilities service covering cleaning, maintenance and compliance for multi-site estates, delivered under a single contract with one account team.",
        trust: "checked",
        by: "Liam Doyle",
        at: "14 July 2026",
      },
      {
        name: "Security and certifications",
        coverage: [9, 13],
        brief:
          "Northgate holds ISO 27001 for the managed service and ISO 14001 for its environmental management. Vetting is to BS 7858 for all site staff.",
        trust: "changed-since-checked",
        review: "A concept this section includes changed on 28 August 2026.",
      },
      {
        name: "Commercial terms",
        coverage: [4, 7],
        brief:
          "Standard and Professional tiers, priced per site per month, with a minimum 24-month term.",
        trust: "unchecked",
      },
    ],
  },
  suggestions: [
    {
      kind: "promotion",
      title: "Save “What is your ISO 27001 scope?” as an Answer",
      from: "Priya Shah",
      when: "11 minutes ago",
      detail: "Closest existing Answer: “Which certifications do you hold?” — judged a variant.",
    },
    {
      kind: "candidate",
      title: "12 candidate concepts from Capability statement 2026.docx",
      from: "better-answers-extract/0.3.1",
      when: "1 hour ago",
      detail: "Kinds introduced: Accreditation. Domain: Company.",
    },
    {
      kind: "edit",
      title: "Add “Also known as: IS27001” to ISO 27001 certification",
      from: "Tom Okafor",
      when: "Yesterday",
      detail: "Confirmed alias. Lands as a body line through the governed write.",
    },
    {
      kind: "candidate",
      title: "3 candidate concepts from Northgate DPA.pdf",
      from: "better-answers-extract/0.3.1",
      when: "Yesterday",
      detail: "One conflict raised: data processing locations.",
    },
  ],
  concepts: [
    {
      title: "ISO 27001 certification",
      kind: "Certification",
      domain: "Company",
      state: "checked",
      by: "Priya Shah",
      at: "3 March 2026",
      owner: "Priya Shah",
    },
    {
      title: "Certified operating centres",
      kind: "Entity",
      domain: "Company",
      state: "checked-by-platform",
      owner: "Priya Shah",
    },
    {
      title: "Data processing locations",
      kind: "Policy",
      domain: "Company",
      state: "out-of-date",
      owner: "Liam Doyle",
    },
    {
      title: "Standard tier response times",
      kind: "Tier",
      domain: "Managed service",
      state: "unchecked",
      owner: "Unassigned",
    },
    {
      title: "BS 7858 vetting",
      kind: "Policy",
      domain: "Company",
      state: "checked",
      by: "Tom Okafor",
      at: "19 June 2026",
      owner: "Tom Okafor",
    },
    {
      title: "Glasgow operating centre",
      kind: "Entity",
      domain: "Company",
      state: "draft",
      owner: "Priya Shah",
    },
  ],
  bindings: [
    {
      name: "Company website",
      connector: "Website",
      sensitivity: "Public",
      docs: 214,
      state: "Published",
      run: "09:12 today",
    },
    {
      name: "Bid library (SharePoint)",
      connector: "SharePoint",
      sensitivity: "Restricted",
      docs: 1840,
      state: "Published",
      run: "08:40 today",
    },
    {
      name: "HubSpot — closed deals",
      connector: "HubSpot",
      sensitivity: "Internal",
      docs: 96,
      state: "Waiting to publish",
      run: "Yesterday",
    },
    {
      name: "ISMS (reference only)",
      connector: "Referenced read",
      sensitivity: "Restricted",
      docs: 0,
      state: "Published",
      run: "Read live",
    },
  ],
};
