/** Audit rows are never rewritten, so a name stays here for good; a new act's name is appended. */
export const STORED_ACT_NAMES = [
  "knowledge.suggestion.declined",
  "knowledge.suggestion.returned",
  "people.person.named",
  "people.person.renamed",
  "people.person.credentials_revoked",
  "people.person.grants_ended",
  "people.person.added",
  "people.operator.granted",
  "people.operator.revoked",
  "people.person.signed_in",
  "people.client.consented",
  "people.person.recovery_codes_issued",
  "people.person.recovery_code_used",
  "people.person.authenticator_added",
  "people.person.authenticator_removed",
  "people.person.passkey_added",
  "people.person.passkey_renamed",
  "people.person.passkey_removed",
  "people.person.second_factor_confirmed",
  "people.person.factors_replaced",
  "people.person.restore_code_accepted",
  "platform.workspace.provisioned",
  "platform.workspace.renamed",
  "people.member.added",
  "people.member.joined",
  "people.group.created",
  "people.group.renamed",
  "people.group.deleted",
  "people.group.member_added",
  "people.group.member_removed",
  "people.member.removed",
  "people.member.role_changed",
  "people.member.credentials_revoked",
  "people.invitation.created",
  "people.invitation.resent",
  "people.invitation.cancelled",
  "people.person.name_flagged",
  "people.name_flag.raised",
  "people.request.asked",
  "people.request.approved",
  "people.request.declined",
  "platform.workspace.marked",
  "platform.reconciler.replayed",
  "knowledge.concept.class_overridden",
  "knowledge.check.imported",
  "knowledge.manifest.written",
  "platform.graph.swept",
  "knowledge.concept.committed",
  "knowledge.suggestion.accepted",
  "sources.finding.restored",
  "sources.document.narrowed",
  "sources.document.special_category_dismissed",
  "sources.binding.bound",
  "sources.binding.published",
  "sources.upload.swept",
  "sources.binding.narrowed",
  "sources.binding.widened",
  "people.subject_request.received",
  "people.erasure.completed",
  "platform.erasure.rehearsed",
  "platform.erasure.replayed",
] as const;

/**
 * Named in the reader's words and valued as rows store it, so a rename moves the name, never the
 * value.
 */
export const STORED_DETAIL_KEYS = {
  setId: "setId",
  grants: "grants",
  workspaceId: "workspaceId",
  method: "method",
  replaced: "replaced",
  authenticatorId: "authenticatorId",
  passkeyId: "passkeyId",
  by: "by",
  adminUserId: "adminUserId",
  role: "role",
  nameChanged: "nameChanged",
  slugChanged: "slugChanged",
  userId: "userId",
  invitationId: "invitationId",
  previousRole: "previousRole",
  replacedByInvitationId: "replacedByInvitationId",
  requesterId: "requesterId",
  corrected: "corrected",
  commitSha: "commitSha",
  iri: "iri",
  contentHash: "contentHash",
  evidenceAgrees: "evidenceAgrees",
  bundleId: "bundleId",
  sensitivity: "sensitivity",
  audience: "audience",
  verificationId: "verificationId",
  generation: "generation",
  nodes: "nodes",
  edges: "edges",
  evidenceCount: "evidenceCount",
  findingId: "findingId",
  documentId: "documentId",
  connectedSourceId: "bindingId",
  findingCount: "findingCount",
  lawfulBasisRecorded: "lawfulBasisRecorded",
  privacyInformationUpdated: "privacyInformationUpdated",
  dpiaReferenced: "dpiaReferenced",
  dpiaHash: "dpiaHash",
  fromSensitivity: "fromSensitivity",
  fromAudience: "fromAudience",
  personId: "personId",
  identifierCount: "identifierCount",
  subjectRequestId: "subjectRequestId",
  locations: "locations",
  erasureRequestId: "erasureRequestId",
  tokens: "tokens",
  fromReplayCopy: "fromReplayCopy",
  findingsBankDetails: "findingsBankDetails",
  findingsDateOfBirth: "findingsDateOfBirth",
  findingsGovernmentIdentifier: "findingsGovernmentIdentifier",
  findingsHomeAddress: "findingsHomeAddress",
  findingsJobTitle: "findingsJobTitle",
  findingsPersonName: "findingsPersonName",
  findingsPersonalContact: "findingsPersonalContact",
  findingsSpecialCategory: "findingsSpecialCategory",
} as const;
